### ISSUE TITLE
Improve readablity/visibility of some icons

### ISSUE THREAD

**Issue by GandalfTheWhite80** [scummvm/scummvm-icons#120]
After #18 and #106 I a made a batch conversion of all icons against a white/black background. I found a bunch of icons I've not found/recognized within first two issues. The changes are all made for a better readability or visibility.

I will make a PullRequest after some time/discussion. There are some icons / changes that maybe discussable.
- sci-kq6 (does the grey shadow help?)
- sci-sq6 (still hardly readable)
- scumm-funpack (white shadow "fun pack")
- stark-tlj (is the grey shadow usefull)
- tsage-ringworld (white shadow caption)

Here is a complete list with the proposed changes (pls use comparision view/I will make a PR later)

- adl-hires5 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/adl-hires5.png)
  - droped a new white shadow (removing black artifacts against a white background)
- agi-kq1 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/agi-kq1.png)
  - droped a new black shadow/border
  - filled the black part of the text with black (was tranparent)
- agi-kq2 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/agi-kq2.png)
  - droped a new black shadow
- agos-pn - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/agos-pn.png)
  - removed some spurious white pixel 
  - droped new white shadow (now antialiased)
- agos-dimp - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/agos-dimp.png)
  - new crop from original image
- agos-puzzle - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/agos-puzzle.png)
  - new crop from original image
- agos-swampy - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/agos-swampy.png)
  - new crop from original image
- bbvs-bbvs - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/bbvs-bbvs.png)
  - remove some spurious greenish pixel
  - droped a new black shadow/border
- cge-soltys - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/cge-soltys.png)
  - removed some spurious white pixel 
- glk-colossaladvjod - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/glk-colossaladvjod.png)
  - removed some spurious white/yellow pixel (text,border)
- glk-enchanter - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/glk-enchanter.png)
  - droped a black shadow text (better readability on white background)
- glk-spellbreaker - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/glk-spellbreaker.png)
  - droped a black shadow on "S" (better readability on white background)
- gob-lit - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/gob-lit.png)
  - removed some spurious white/yellow pixel (rigging/text)
- gob-littlered - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/gob-littlered.png)
  - droped a white shadow on the caption (readability on black background)
  - removed some spurious white pixel
- hdb-hdb - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/hdb-hdb.png)
  - removed some spurious white pixel
  - droped a white shadow
- hugo-hugo1 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/hugo-hugo1.png)
  - removed some spurious grey pixel
- hugo-hugo3 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/hugo-hugo3.png)
  - removed some spurious white pixel
- myst3-myst3 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/myst3-myst3.png)
  - removed some spurious white pixel
- plumbers-plumbers - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/plumbers-plumbers.png)
  - removed some spurious white pixel
- prince-prince - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/prince-prince.png)
  - removed some spurious white pixel
- private-private-eye - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/private-private-eye.png)
  - removed transparency of some pixel (top caption/philip marlowe icon)
- saga-ite - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/saga-ite.png)
  - removed some spurious white pixel
- sci-jones - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sci-jones.png)
  - removed some spurious white pixel
  - droped black shadow (around white parts)
- sci-kq6 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sci-kq6.png)
  - removed some spurious red pixel
  - droped grey shadow around caption (better readability black background)
- sci-pepper - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sci-pepper.png)
  - dropded light black shadow around the top head
- sci-qfg4 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sci-qfg4.png)
  - removed some spurious white pixel/areas
- sci-sq4 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sci-sq4.png)
  - removed some spurious white pixel
- sci-sq6 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sci-sq6.png)
  - ~~dropded a white shadow on the black/dark caption (better readability on black background)~~
  - created a new version thx to @dotdc 
- sci-torin - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sci-torin.png)
  - removed some spurious yellow pixel
- scumm-arttime - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-arttime.png)
  - droped light white shadow (pen)
  - droped light black shadow (glue/paper)
- scumm-baseball2001 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-baseball2001.png)
  - removed some spurious white pixel
- scumm-basketball - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-basketball.png)
  - removed some spurious white pixel
- scumm-brstorm - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-brstorm.png)
  - dropd black shadow (ballons)
  - removed some spurious white pixel
  - better white gradiation by @Tucky27
- scumm-football2002 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-football2002.png)
  - removed some spurious white pixel
- scumm-funpack - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-funpack.png)
  - removed some spurious grey pixel
  - droped a white shadow on "fun pack" caption
- scumm-pass - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-pass.png)
  - removed some spurious white pixel/area
  - created a new white shadow (around black parts)
  - droped black shadow "to adventure"
- scumm-puttmoon - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-puttmoon.png)
  - droped black shadow (eye brows/tyre)
- stark-tlj - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/stark-tlj.png)
  - removed spurious white pixel
  - droped light grey shadow
- sword25-sword25 - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sword25-sword25.png)
  - removed spurious white pixel
- teenagent-teenagent - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/teenagent-teenagent.png)
  - removed spurious white pixel
- tsage-ringworld - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/tsage-ringworld.png)
  - droped white shadow around caption (better readability against a black background)
- tucker-tucker - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/tucker-tucker.png)
  - removed spurious white pixel
  - droped a light white shadow (black caption)
- zvision-zgi - [compare view old/new](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/zvision-zgi.png)
  - removed spurious white pixel
  - added white shadow (blue caption)
  - added rays of light

The original authors are (according to toc.md) - It would be nice if you have a closer look on your work/the changes. Pls say if the modifications are not OK for you :-) :-(
@TrivialBalderdash, @dotdc , @nightm4re94 , @JenniBee , @SupSuper , @Urgeistenergie, @robertmegone, @Tucky27

**Comment by Tucky27** [comment]
Regarding scumm-football2002 that isn't some white pixel but what is apart of the original cover image - its a part of the football shadow but is lighter on original image.
![backyard-football-2002-macintosh-front-cover](https://user-images.githubusercontent.com/61733979/151944291-32feb728-2edb-47d1-94e2-d44740591f57.jpg)
.

**Comment by GandalfTheWhite80** [comment]
Thx @Tucky27 - updated the [image](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-football2002.png)

**Comment by TrivialBalderdash** [comment]
@GandalfTheWhite80 - Great updates to adl-hires5.  Thanks for taking the time to improve these icons.

**Comment by dotdc** [comment]
Hi @GandalfTheWhite80, the updates on the ones I made are great! 

- `sci-kq6` the grey shadow doesn't help a lot, it's about the same for me.
- `sci-sq6` is better but still not perfect, maybe it's worth re-doing it?

Original Space Quest 6 cover: 

![sq6](https://user-images.githubusercontent.com/12827900/152117315-2d606376-70a9-4594-9341-b5cf76123593.JPEG)

**Comment by GandalfTheWhite80** [comment]
@dotdc  The for the original cover - i'll give it a ray after work :-) (agree with you on re-doing!)


sci-kq6 - I added the "new" icon in the icons.dat. I think there is a difference in the new scummvm grid view. What is your opion? 
![sci-kq6-scummview](https://user-images.githubusercontent.com/71585967/152121608-29748d38-1f41-4f87-a979-289857569c4e.png)

**Comment by GandalfTheWhite80** [comment]
@Tucky27 I will upload pngs to my branch toda (in the evening) - if needed I could provide you with xcf files (Gimp - normally I would add shadow etc. as an extra layer...)

**Comment by GandalfTheWhite80** [comment]
Launch time version of sc-isq6 :-)

![sci-sq6-test](https://user-images.githubusercontent.com/71585967/152161832-6295971e-5f23-4b0c-8432-bfd43eb3baca.png)

**Comment by dotdc** [comment]
Agree, King's Quest VI icon is better at small size and it's probably overall easier to read the title.
Awesome new icon for Space Quest 6! :fire:

**Comment by GandalfTheWhite80** [comment]
@Tucky27  Uploaded the pngs to https://github.com/GandalfTheWhite80/scummvm-icons/tree/GandalfTheWhite80-patch-120/icons - You can add your further improved versions here and I will add them (update them) in my branch so we can make one large commit (if it's ok for you)

**Comment by GandalfTheWhite80** [comment]
Here is another version of sci-kg6

![sci-kq6a](https://user-images.githubusercontent.com/71585967/152199870-2183c20d-bd30-4c40-96e3-6360078adda2.png)
6

**Comment by GandalfTheWhite80** [comment]
Here goes another test (last one for today)

which one do you like best (hopefully mid or right :-))

![zvision-zgi-v5](https://user-images.githubusercontent.com/71585967/152204702-ea431b0a-eeef-4b93-a535-bf0210614d4f.png)

**Comment by Tucky27** [comment]
> @Tucky27 I will upload pngs to my branch today (in the evening) - if needed I could give you the xcf files (Gimp - normally I would add shadow etc. as an extra layer...)

Thanks for making those available. Could I get the xcf of sorcerer, mostly so I can grab the shadow layer which I can then just drop into my existing xcf.

**Comment by Tucky27** [comment]
I'm not sure if adding my updated scumm-brstorm.png will over-write yours so I'll add a zip here.
[scumm-brstorm.zip](https://github.com/scummvm/scummvm-icons/files/7990618/scumm-brstorm.zip)

**Comment by GandalfTheWhite80** [comment]
Updated [scumm-brstrom](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-120/icons/scumm-brstorm.png) ([compare view](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-brstorm.png))

XCF for DL (glk-sorcerer wasn't changed) 
* [glk-enchanter.xcf](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/glk-enchanter.xcf)
* [glk-spellbreaker.xcf](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/glk-spellbreaker.xcf)

**Comment by dotdc** [comment]
@GandalfTheWhite80 The last King's Quest VI version is way better :+1: 
I prefer the right version Zork Grand Inquisitor. Hope the light ray effect fits well in the UI, otherwise mid.

**Comment by GandalfTheWhite80** [comment]
Replaced some arbitrary icons with the 3 (old/new/new2) zork icons @dotdc 
![image](https://user-images.githubusercontent.com/71585967/152307837-27673e2e-2a29-412e-9844-3d28f0e0c28e.png)

**Comment by dotdc** [comment]
Still prefer the right one!

**Comment by Tucky27** [comment]
> Updated [scumm-brstrom](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-120/icons/scumm-brstorm.png) ([compare view](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/scumm-brstorm.png))
> 
> XCF for DL (glk-sorcerer wasn't changed)
> 
>     * [glk-enchanter.xcf](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/glk-enchanter.xcf)
> 
>     * [glk-spellbreaker.xcf](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/glk-spellbreaker.xcf)

Thanks for that.

**Comment by GandalfTheWhite80** [comment]
Updatet all compre view icons - added scummvm default background color.

I Think a will make a PR tomorrow.
