### ISSUE TITLE
Engine icons

### ISSUE THREAD

**Issue by trembyle** [scummvm/scummvm-icons#128]
Engine icons are used by default when there is no individual game icon. Can we add some to the icon repo?

https://github.com/scummvm/scummvm/pull/2975

Some of the most used engines like SCI and SCUMM already have a lot of individual game icons. Engines such as AGS, GLK, and Director, which support a huge number of games, could benefit from this.

**Comment by trembyle** [comment]
For some reason the link for the relevant PR does not open in the GitHub app for me. It works fine on the webpage.

**Comment by Thunderforge** [comment]
Which engine icons do we need?

**Comment by trembyle** [comment]
I'm thinking of engines that allow you to run a huge number of games. So, as I mentioned above, AGS, GLK, and Director. Also Wintermute would be a good one. SCUMM, AGI, SCI have a lot of fan games that may not have individual icons.

**Comment by trembyle** [comment]
Now I'm changing my mind a little bit. In addition to the above, there should be icons for at least the Sierra and LucasArts engines as well. The users, some of whom are superfans like me 😁, would expect to see them.

Here's an example of a Sierra logo that would be appropriate for SCI. Note the correct aspect ratio.

![image](https://user-images.githubusercontent.com/54326852/153467428-9846c61d-6fce-494a-888c-14acf21e3a69.png)

One convenient aspect of Sierra games being spread across three engines (`adl`,`agi`,`sci`) is that we can use logos from different eras. This one would work well for `adl`. Some platforms used a colorized logo, but IMO monochrome would be more appropriate. It calls back to the earlier monochrome design for the On-Line Systems logo (the original name of the company).

![image](https://user-images.githubusercontent.com/54326852/153468519-41a17df8-b069-43a4-861f-fcefce95cdf0.png)

I consider this to be the classic LucasArts logo. Some others might prefer an earlier one that says LucasFilm Games. Maybe we use this one for the `grim` engine and a LucasFilm one for `scumm`?

![image](https://user-images.githubusercontent.com/54326852/153467873-a1a3a308-1d9f-4ba1-8a21-8731b768e8ae.png)

**Comment by trembyle** [comment]
There is no specific logo for GLK, which is an open standard. The canonical GLK software is called Gargoyle. This is the graphic on Tor Andersson's page. It doesn't really lend itself to an icon.

![image](https://user-images.githubusercontent.com/54326852/153469844-f49f94d7-bdf6-472d-89f9-2f7cd0d6ef63.png)

Ideally we could reference the GLK subengine for this, which would allow us to use company logos in many cases. However, this is not yet implemented. I would *not* want to use Infocom, for example, to stand in for all interactive fiction.

So my thought is to use a new representative design for `glk`. Something to represent a text parser, or maybe the idea of conjuring images in your head as you play?

Yet another idea is to steal (or ask permission to use) the IF Technology Foundation's logo.

![image](https://user-images.githubusercontent.com/54326852/153470484-c5d76896-7197-4307-a706-caa68e3a5ad6.png)

**Comment by trembyle** [comment]
AGS logo is easy. The provide the asset for you on their webpage.

![image](https://user-images.githubusercontent.com/54326852/153471042-7b43b816-ef6f-406c-97ae-88f97503280d.png)

Wintermute logo is also easy to find.

![image](https://user-images.githubusercontent.com/54326852/153471952-e8e403f9-7312-4828-a364-3d24ad0e49d1.png)

As for Director, they used two significant logos over the years. Personally I think the earlier one resonates with people more. Also, we currently support only earlier versions of Macromedia's engine, and so the later logo wasn't in use yet.

![image](https://user-images.githubusercontent.com/54326852/153471483-a401eb96-5d21-4f1d-97a4-9429e37bed76.png)

**Comment by henke37** [comment]
The `sludge` engine has its green splat.
![Sludge_128x128x32](https://user-images.githubusercontent.com/4971363/153473880-a1b99d17-dd83-4bf2-a123-5b19db265cf3.png)

**Comment by trembyle** [comment]
This one could work for the `gob` engine.

![image](https://user-images.githubusercontent.com/54326852/153475397-7af3f564-27be-4700-ba7b-ccf23243b117.png)

**Comment by trembyle** [comment]
The image at the top here represents the Magic Tales series from Animation Magic. I can be used for the `composer` engine. There might be a cleaner version of it somewhere.

![image](https://user-images.githubusercontent.com/54326852/153476448-9fcb6f3f-4827-43fe-b101-e67753575961.png)

**Comment by henke37** [comment]
How about something for the `testbed` engine? The standard clipboard with checkboxes?

**Comment by GandalfTheWhite80** [comment]
Do the same restrictions apply to engine icons (size, png with alpha)?

**Comment by henke37** [comment]
The idea is that they are used as fallbacks if the game doesn't have a logo, so yes, they have the same requirements.

**Comment by GandalfTheWhite80** [comment]
I think the ps2 logo must be thicker somehow
![PlayStation_2_logo_v2](https://user-images.githubusercontent.com/71585967/153483754-1dbde71c-f2ad-413a-9a4d-7bb3f2669de9.png)

**Comment by GandalfTheWhite80** [comment]
2nd try..
![PlayStation_2_logo_v2a](https://user-images.githubusercontent.com/71585967/153486061-5938e401-a050-4349-b18a-f97e8d9a989f.png)
.

**Comment by trembyle** [comment]
> Do we need a composer engine logo?

There are more games - potentially a lot more games. See the notes starting a V5, and also note that we don't have anything listed for V3-V4. Plus there are a lot of JumpStart games to check.

https://wiki.scummvm.org/index.php?title=Composer

**Comment by trembyle** [comment]
@GandalfTheWhite80
> I think the ps2 logo must be thicker somehow

Could you please keep the platform work that you're doing out of this thread? This is intended for discussion of engine icons. Happy to see the progress though!

**Comment by henke37** [comment]
Just add a member function to the `MetaEngineDetection` class that returns the icon to use?

**Comment by Tucky27** [comment]
@trembyle Do the engine, flag, platform icons have to be overlaid over the game icon itself? Would it be possible for them to appear on the side or under the game icon? My concern is that with many icons overlaid onto the game icon that it ends up looking messy overall.

**Comment by GandalfTheWhite80** [comment]
@Tucky27 I agree with you. We have the language and the platform icon as overlay another overlay is to much. Also some of the icons @trembyle won't work with dark/light backgrounds. I will upload compare views later.

Couldn't we just use them as a default engine icon? Or maybe we could use them as an icon for the engine groupings - currently there is only a text separator with the engine name.

**Comment by trembyle** [comment]
There may be some confusion here. This is not an overlay. The engine icon is used as a fallback when a game icon doesn't exist.

**Comment by trembyle** [comment]
> Just add a member function to the `MetaEngineDetection` class that returns the icon to use?

@henke37 Yes, I think that would work. I'd like to experiment with it a bit to ensure we're calling that function in the right contexts.

**Comment by GandalfTheWhite80** [comment]
Made a few compare views against different backgrounds...

- ags - [compare view](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/ags.png)
  - does not work with light backgrounds
- composer - [compare view](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/composer .png)
  - just fine (maybe a little bit to small - larger scan available?)
- macromedia - [compare view](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/macromedia.png)
  -does not work with dark backgrounds
- sludge - [compare view](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/sludge.png)
  -have some extra white (half transparent pixel - visible agains dark backgrounds)
- wintermute - [compare view](https://github.com/GandalfTheWhite80/scummvm-icons/blob/GandalfTheWhite80-patch-oldvsnew/icons/oldVsNew/wintermute.png)
  - so so good against the def. scummVM Background color (thumbs/grid view)

Just to make it clear - this are just test. If you have new icon ideas I will make further versions for this discussion :-)

- Sierra - do we have any icon with a higher res?
- GLK - any idea?
- Lucas (Arts/Film) - one logo for both?

**Comment by GandalfTheWhite80** [comment]
I will commit these 5 enigine icons later if no one objects.
![ags](https://user-images.githubusercontent.com/71585967/154949982-70690bcd-d673-45ad-9a63-0d7a9ab8a814.png)
![composer](https://user-images.githubusercontent.com/71585967/154949985-566218cd-10e8-4c84-b0fb-5bca86dde6e1.png)
![macromedia](https://user-images.githubusercontent.com/71585967/154949987-70b0b925-560f-4780-9f78-898814c07ec5.png)
![sludge](https://user-images.githubusercontent.com/71585967/154949988-3ece5dda-1b03-4b0a-8eaf-2100d4d760c6.png)
![wintermute](https://user-images.githubusercontent.com/71585967/154949989-df40306f-db26-4773-abce-8b6d03bdf084.png)

**Comment by GandalfTheWhite80** [comment]
@trembyle The first one as sci and the second as adl - was that your suggestion?
![sci](https://user-images.githubusercontent.com/71585967/155001003-e4cfb340-f522-4128-9130-445efeb26abc.png)
![adl](https://user-images.githubusercontent.com/71585967/155001014-01cfeaef-dc58-4a26-9805-54af45519d82.png)

**Comment by Thunderforge** [comment]
We now have icons for

* ADL
* AGS
* Composer
* Director
* GLK
* Gob
* SCI
* Scumm
* Sludge
* Wintermute

I think the only ones that are missing that we could realistically have a need for fallbacks is AGI.

If we add an AGI icon, can we close this issue? Or are there other engines we need to add icons for?

**Comment by Tucky27** [comment]
Does Hypno engine have an icon?

**Comment by Thunderforge** [comment]
It seems to me that if we have an icon for all the games that can be detected for an engine, it will never show up. Thus we only need it for engines with fan games (e.g. AGI) or engines with a boatload of published games (e.g. Wintermute, AGS).

My understanding is that there were only a handful of games published for Hypno. If we created icons for the six or so games, then the user will never see a Hypno engine icon, correct?

**Comment by Thunderforge** [comment]
To clarify, I don't think we need a dedicated icon for AGI fangames, just an icon for the AGI engine in general, which fan games will use.

**Comment by Tucky27** [comment]
> To clarify, I don't think we need a dedicated icon for AGI fangames, just an icon for the AGI engine in general, which fan games will use.

Got it. I'm surprised we don't have one already.

**Comment by GandalfTheWhite80** [comment]
There have been a few proposuals as far as i can remember (discord)

**Comment by Thunderforge** [comment]
The options seem to be:

* An old-fashioned Sierra logo
* A custom icon, like we have for SCUMM
* Some sort of word art

The Sierra logo is recognizable, but could be confused with SCI or an officially produced Sierra game. The other alternatives are less likely to be confused, but there’s a question on how to make it.

**Comment by Tucky27** [comment]
Maybe the AGI logo could incorporate the Sierra mountain like the classic Sierra logo. It would help make it recognisable at least.

**Comment by Tucky27** [comment]
Discord seems to be down. Here is a first attempt at an AGI logo. Feedback welcome.
![AGI-logo](https://user-images.githubusercontent.com/61733979/174737581-99296e43-bf8f-4fcc-9622-e11874fbbc00.png)

**Comment by Thunderforge** [comment]
AGI was added in 0f46900

There were plans for a corresponding SCI logo to replace the existing SCI logo (which is the Sierra logo, ambiguous about which engine it refers to). If we can add that, I think this issue can be closed.

**Comment by GandalfTheWhite80** [comment]
@Tucky27 You proposed an SCI logo in discord right?

**Comment by GandalfTheWhite80** [comment]
added the  sci icon - Thx Tucky27.

**Comment by Thunderforge** [comment]
Now that we have engine icons for all engines that we reasonably expect fallbacks for (due to fangames, etc), I think we can close this issue.
