### ISSUE TITLE
ICONS: Add icon for The Phantom Fellows Demo

### ISSUE THREAD

**Issue by thevolumeremote** [scummvm/scummvm-icons#141]
Just noticed the demo version needs an icon! 
Game ID: phantomfellows-demo
Engine: AGS
[ags-phantomfellows-demo.png.zip](https://github.com/scummvm/scummvm-icons/files/8149178/ags-phantomfellows-demo.png.zip)

**Comment by GandalfTheWhite80** [comment]
I have a few questions @thevolumeremote:
- is the current ags-phantomfellows not working for you / for the demo?
- or is there any other problem with the current gs-phantomfellows?

The game grid view will only use the <engineid>-<gameid> version as far as I can see (see discord icons disussions).

**Comment by thevolumeremote** [comment]
Hi @GandalfTheWhite80 

As of now, loading the demo in ScummVM with the icon path set, does not link the game to an icon. 
The game works great, no other problems,

The Phantom Fellows full version isn't released yet. With that said and since I cannot test the full version, I made an assumption that because the demo versions game ID is ags-thephantomfellows-demo and the icon's ID (eludes to a full version) being only ags-thephantomfellows, that perhaps if the demo ID had an icon with a matching ID, then the icon would work for the game.

Here is a[ link ]https://www.dropbox.com/s/7e7o9w24hwnuqbv/The%20Phantom%20Fellows%20Demo.zip?dl=1(url) to the demo if you'd like to see :)

**Comment by GandalfTheWhite80** [comment]
I will dl / install it and have look.

**Comment by GandalfTheWhite80** [comment]
Ok - when I add the dome the "game id" in the gui is demo. But the grid will show me the correct icon/cover view:

![image](https://user-images.githubusercontent.com/71585967/156044814-7b7bd82c-5339-4b55-8acd-4bafba8ddf47.png)

**Comment by GandalfTheWhite80** [comment]
Have downloaded the icons (gui-icons-20211112.dat must be in your icons dir)?

**Comment by thevolumeremote** [comment]
Hi @GandalfTheWhite80 thank you for checking it out! Unfortunately, I'm not having luck. I do have gui-icons-20211112.dat in my icon path and the other games icons are working. Come to think of it, the icon used to work on my end but alas, I cannot think of any reason for things to have changed on my end (yet).

I did also try to load the game in a Git build on Windows and then iOS- with the same result, all other games icons work except this one.

Let me know if there is anything you can think of and I'll keep trying. FWIW my icon path with the .dat file in it, is a folder called ScummVM Extras and it is in my documents folder. I downloaded the dat file from https://downloads.scummvm.org/frs/icons/
![ss](https://user-images.githubusercontent.com/57506666/156116277-fc3479ee-b808-4b88-b837-d682be1942a9.JPG)

**Comment by thevolumeremote** [comment]
I looked inside the dat file I downloaded and I don't see any AGS game icons in it.
I had downloaded the dat file from https://downloads.scummvm.org/frs/icons/ because I couldn't get it to compile on my end from the repo (running gen-set.py). That said, it seems that python script downloads the dat file from the same location I got mine, so I'm not sure why mine doesn't have AGS icons in it and I assume yours does... Anyway I hope this helps in some way, I'll resume investigating in the morning :)
<img width="1010" alt="Untitled" src="https://user-images.githubusercontent.com/57506666/156117250-063aaea8-a930-439d-8042-955a252c79cc.png">

**Comment by GandalfTheWhite80** [comment]
@thevolumeremote  yes sry - the icon was added after the creation of the dat file :-(. I fiddled around somehow with my local dat. Sry for that.

You can just add the png to your dat an restart scumm. With the next update (hopefully not to far in the future) of the dat file the icon will be there for all.

I will close the issue if there is no other problem (sry for the confusion with my local file)

**Comment by thevolumeremote** [comment]
@GandalfTheWhite80  no worries at all mate! When I said I recalled it working a few builds ago, it turns out that was because I fiddled with my dat file and forgot lol 

Anyway, thank you for all of your help! 

Oh I guess while this is open, and if it’s not much trouble, would you mind swapping out the icon for The Phantom Fellows to the newer one? I’ll reattach it here for ease and if it’s at all a pain or inconvenience then don’t worry about it :)
[TPF_ScummVM_Icon.zip](https://github.com/scummvm/scummvm-icons/files/8164155/TPF_ScummVM_Icon.zip)

**Comment by GandalfTheWhite80** [comment]
PS You don't need the "-demo" version.. the png without version will do the trick.
