### ISSUE TITLE
scumm-chase icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#145]
[scumm-chase.zip](https://github.com/scummvm/scummvm-icons/files/8158470/scumm-chase.zip)
![scumm-chase](https://user-images.githubusercontent.com/61733979/156096817-35b7b2db-b573-4ba2-a7bf-be34a95822e7.png)

**Comment by Tucky27** [comment]
Apologies for asking this to be updated again. I realised the original one I did was a little rough around the edges.

**Comment by GandalfTheWhite80** [comment]
Updated this icon - thx.

PS Removed some extra grey pixel top left corner (before the commit)
