### ISSUE TITLE
ICONS: Add icon for Astro Chicken

### ISSUE THREAD

**Issue by thevolumeremote** [scummvm/scummvm-icons#147]
(for your consideration...)
ID: sci-astrochicken
[sci-astrochicken.png.zip](https://github.com/scummvm/scummvm-icons/files/8164290/sci-astrochicken.png.zip)

**Comment by thevolumeremote** [comment]
Absolutely! When I get home this evening I’ll send another with transparency and perhaps an alternate version w the arcade screen frame :)

**Comment by GandalfTheWhite80** [comment]
Ok - in the meantime.. I gave it a try (first impression)...
![sci-astrochicken-ovn](https://user-images.githubusercontent.com/71585967/156430712-265a6c70-4071-4a6f-8d8d-65c2c42586ab.png)

**Comment by GandalfTheWhite80** [comment]
Im locking forward to the arcade screen frame :-)

**Comment by thevolumeremote** [comment]
@GandalfTheWhite80 those look great mate! I played around a bit, let me know what you think of this :)
[sci-astrochicken.png.zip](https://github.com/scummvm/scummvm-icons/files/8175074/sci-astrochicken.png.zip)

**Comment by thevolumeremote** [comment]
![sci-astrochicken](https://user-images.githubusercontent.com/57506666/156499706-a3894faa-f5d5-4d5f-b93a-1ce9a70a0fa6.png)

**Comment by thevolumeremote** [comment]
Here it is reversed:)
[sci-astrochicken.png 2.zip](https://github.com/scummvm/scummvm-icons/files/8175132/sci-astrochicken.png.2.zip)

**Comment by thevolumeremote** [comment]
![sci-astrochicken](https://user-images.githubusercontent.com/57506666/156500611-789215ea-0878-4f6b-8ba3-3cb343f8ad19.png)

**Comment by GandalfTheWhite80** [comment]
Relly n1 one. Here is a comparison of the 2 versions (changed your last slightly, hope that's ok)
![sci-astrochicken-ovn2](https://user-images.githubusercontent.com/71585967/156597373-bf2272bb-aff8-43b1-af25-2892a6a90753.png)
 
 left or right?

**Comment by thevolumeremote** [comment]
@GandalfTheWhite80 looks great mate! Having a hard time deciding, decided to do one more....
![sci-astrochicken](https://user-images.githubusercontent.com/57506666/156631912-a066bc12-95ab-4053-95e8-32820302ee95.png)

**Comment by thevolumeremote** [comment]
[sci-astrochicken.png.zip](https://github.com/scummvm/scummvm-icons/files/8180322/sci-astrochicken.png.zip)

**Comment by GandalfTheWhite80** [comment]
Do you want the top/bottom part to be transparent?

**Comment by thevolumeremote** [comment]
Whichever you prefer mate! I exported it with 80% transparency for you, if you prefer it. I'd be happy to adjust!
![astrochicken 2](https://user-images.githubusercontent.com/57506666/156633831-dbde8950-041f-41d7-a7ee-58175b2f2a1a.png)

**Comment by thevolumeremote** [comment]
[sci-astrochicken.png.zip](https://github.com/scummvm/scummvm-icons/files/8180398/sci-astrochicken.png.zip)

**Comment by GandalfTheWhite80** [comment]
Time to choose - you are the committer so which one do you like most?
![sci-astrochicken-comp](https://user-images.githubusercontent.com/71585967/156801270-f80ddfb2-c636-4e83-8dd5-5f0c5d5dd608.png)

**Comment by thevolumeremote** [comment]
Aw you’re much too kind, thank you for the honors mate!! And thank you for loading them up so I can see them with the flags. That said, for clarity of the OS and region flag, I’ll pick the 3rd one :)

**Comment by GandalfTheWhite80** [comment]
Thx for your contribution - adeded it.

BTW you can test icons by yourself, just open the icons-dat with 7z (for example) and add your new icon.
