### ISSUE TITLE
glk-amfv icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#148]
[glk-amfv.zip](https://github.com/scummvm/scummvm-icons/files/8177539/glk-amfv.zip)
![glk-amfv](https://user-images.githubusercontent.com/61733979/156559164-b0e70d69-b7b8-442d-81b0-32c9edb6c97d.png)

**Comment by GandalfTheWhite80** [comment]
Thx again - a really n1 icon!
