### ISSUE TITLE
composer-littlesamurai icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#153]
[composer-littlesamurai.zip](https://github.com/scummvm/scummvm-icons/files/8189933/composer-littlesamurai.zip)
![composer-littlesamurai](https://user-images.githubusercontent.com/61733979/156866897-5cdda788-6a1f-4e79-bb84-c0ed3b81941a.png)

**Comment by GandalfTheWhite80** [comment]
added - thx again :-)
