### ISSUE TITLE
composer-sleepingcub icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#154]
[composer-sleepingcub.zip](https://github.com/scummvm/scummvm-icons/files/8189919/composer-sleepingcub.zip)
![composer-sleepingcub](https://user-images.githubusercontent.com/61733979/156866574-fb86774d-3b82-4b0e-943c-c16007eb7047.png)

**Comment by GandalfTheWhite80** [comment]
added - thx again :-)
