### ISSUE TITLE
glk-sorcerer and scumm-readtime Icon Updates

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#156]
[glk-sorcerer.zip](https://github.com/scummvm/scummvm-icons/files/8190399/glk-sorcerer.zip)
![glk-sorcerer](https://user-images.githubusercontent.com/61733979/156878080-f0a82745-7134-4984-a6f5-bd12349fe169.png)
[scumm-readtime.zip](https://github.com/scummvm/scummvm-icons/files/8190400/scumm-readtime.zip)
![scumm-readtime](https://user-images.githubusercontent.com/61733979/156878099-84373496-caa7-41fc-97bd-2bda02ecb6f4.png)

**Comment by GandalfTheWhite80** [comment]
@Tucky27 Don't you want to join the discord scummvm#icon-channel discussion?

**Comment by GandalfTheWhite80** [comment]
Thx again / updated.

**Comment by Tucky27** [comment]
> @Tucky27 Don't you want to join the discord scummvm#icon-channel discussion?

I'm on Discord as Andrew T
