### ISSUE TITLE
glk-savageisland1&2 icons

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#159]
[glk-savageisland1.zip](https://github.com/scummvm/scummvm-icons/files/8196555/glk-savageisland1.zip)
[glk-savageisland2.zip](https://github.com/scummvm/scummvm-icons/files/8196558/glk-savageisland2.zip)
![glk-savageisland1](https://user-images.githubusercontent.com/61733979/157006807-0f91aa7b-2234-4036-a105-47bcd2115704.png)
![glk-savageisland2](https://user-images.githubusercontent.com/61733979/157006823-d882f166-ee77-4ec6-ae66-d775d1ff4d94.png)

**Comment by GandalfTheWhite80** [comment]
Done - Thx again :-)
