### ISSUE TITLE
glk-claymorguesorcerer icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#160]
[glk-claymorguesorcerer.zip](https://github.com/scummvm/scummvm-icons/files/8197049/glk-claymorguesorcerer.zip)
![glk-claymorguesorcerer](https://user-images.githubusercontent.com/61733979/157017358-641e75f0-7467-4a5c-bd3a-2eeb98ca4343.png)

**Comment by GandalfTheWhite80** [comment]
Done - Thx again :-)
