### ISSUE TITLE
glk-buckaroobanzai icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#161]
[glk-buckaroobanzai.zip](https://github.com/scummvm/scummvm-icons/files/8197380/glk-buckaroobanzai.zip)
![glk-buckaroobanzai](https://user-images.githubusercontent.com/61733979/157026926-1384a66b-9fb5-4618-9adc-a4e8e679718c.png)

**Comment by GandalfTheWhite80** [comment]
added
