### ISSUE TITLE
glk-ghosttown icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#167]
[glk-ghosttown.zip](https://github.com/scummvm/scummvm-icons/files/8213694/glk-ghosttown.zip)
![glk-ghosttown](https://user-images.githubusercontent.com/61733979/157420499-15e86491-79cd-438d-8fa3-2570f09c12ab.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
