### ISSUE TITLE
glk-goldenvoyage icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#168]
[glk-goldenvoyage.zip](https://github.com/scummvm/scummvm-icons/files/8213380/glk-goldenvoyage.zip)
![glk-goldenvoyage](https://user-images.githubusercontent.com/61733979/157412719-52824774-380a-4597-9f2f-deb4eb21a75c.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
