### ISSUE TITLE
glk-voodoocastle icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#169]
[glk-voodoocastle.zip](https://github.com/scummvm/scummvm-icons/files/8219655/glk-voodoocastle.zip)
![glk-voodoocastle](https://user-images.githubusercontent.com/61733979/157573551-936a5c9e-3420-4720-b3e9-b17b8d700f69.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
