### ISSUE TITLE
Please re-add the Level 9 and Magnetic Scrolls games (glk)

### ISSUE THREAD

**Issue by Kirtai** [scummvm/scummvm-icons#17]
The games by Level 9 and Magnetic Scrolls did have boxed commercial releases. Please re-add them to the glk list. I used to have several L9 and one MS game box.

I *think* the Scott Adams adventures did too but am not sure.

**Comment by JenniBee** [comment]
Yeah, The Scott Adams Adventures did have a cover. There were a few more too - Colossal Cave Adventure did on a few of those platforms, so the icon could be used on the _MANY_ engines to which it has been ported.

**Comment by SupSuper** [comment]
Thanks, I'll add the games back as I run into them. It's easier to start small and add as we go along, then have a listing of thousands scaring contributors off.
