### ISSUE TITLE
glk-strangeodyssey icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#170]
[glk-strangeodyssey.zip](https://github.com/scummvm/scummvm-icons/files/8219706/glk-strangeodyssey.zip)
![glk-strangeodyssey](https://user-images.githubusercontent.com/61733979/157575042-f1a21193-f1c2-4770-8bb7-16b25dfd4c23.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
