### ISSUE TITLE
glk-mysteryfunhouse icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#171]
[glk-mysteryfunhouse.zip](https://github.com/scummvm/scummvm-icons/files/8219773/glk-mysteryfunhouse.zip)
![glk-mysteryfunhouse](https://user-images.githubusercontent.com/61733979/157577176-31b8755f-52e2-4a49-87dd-927b84472e8c.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
