### ISSUE TITLE
glk-pirateisle and glk-pyramidofdoom icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#172]
[glk-pirateisle.zip](https://github.com/scummvm/scummvm-icons/files/8220697/glk-pirateisle.zip)
[glk-pyramidofdoom.zip](https://github.com/scummvm/scummvm-icons/files/8219949/glk-pyramidofdoom.zip)
![glk-pirateisle](https://user-images.githubusercontent.com/61733979/157597471-0872b2f4-d303-4e2f-a7b0-552fe51e4d38.png)
![glk-pyramidofdoom](https://user-images.githubusercontent.com/61733979/157581303-01af0f91-04eb-4d58-853d-2f1c67f7c9b6.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
