### ISSUE TITLE
glk-marveladventure icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#173]
[glk-marveladventure.zip](https://github.com/scummvm/scummvm-icons/files/8237166/glk-marveladventure.zip)
![glk-marveladventure](https://user-images.githubusercontent.com/61733979/158007024-21a793cd-4750-41b7-963e-321975780378.png)

**Comment by GandalfTheWhite80** [comment]
Thx again - btw (really just for interesst) where do you find the images? I could also add some if there is a "useable" src :-)

**Comment by Tucky27** [comment]
I usually do a google image search. This was where I found this image. Scroll down for the images.

https://www.trs-80.com/wordpress/emulation-scott-adams/
