### ISSUE TITLE
scumm-freddisfunshop icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#176]
[scumm-freddisfunshop.zip](https://github.com/scummvm/scummvm-icons/files/8250213/scumm-freddisfunshop.zip)
![scumm-freddisfunshop](https://user-images.githubusercontent.com/61733979/158307482-63737aab-38af-4a63-9e82-dd73b3cf7859.png)

**Comment by GandalfTheWhite80** [comment]
Thx again
