### ISSUE TITLE
Icon Updates sci-msastrochicken & scumm-freddisfunshop

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#177]
Just some minor updates to fix some errant pixels
[sci-msastrochicken.zip](https://github.com/scummvm/scummvm-icons/files/8257582/sci-msastrochicken.zip)
![sci-msastrochicken](https://user-images.githubusercontent.com/61733979/158481921-ed0a9912-fb76-441d-b632-9558e7511e54.png)
[scumm-freddisfunshop.zip](https://github.com/scummvm/scummvm-icons/files/8257628/scumm-freddisfunshop.zip)
![scumm-freddisfunshop](https://user-images.githubusercontent.com/61733979/158483389-00037915-0bfb-4d62-8b7d-56d39ac8fca2.png)

**Comment by GandalfTheWhite80** [comment]
updated the icons :-).
