### ISSUE TITLE
Spurious white pixels

### ISSUE THREAD

**Issue by Kirtai** [scummvm/scummvm-icons#18]
Quite a few of the icons have spurious white borders and extra pixels which make them look bad on a non-white background.

**Comment by JenniBee** [comment]
Most of those are probably mine (I used to use Paint.NET and I use Photoshop now, plus my skills have grown since I started contributing those to the original thread years ago).  Can you provide a list of icons where this is the case?  I'll go through and fix those that are mine.

**Comment by GandalfTheWhite80** [comment]
Currently: 

- tinsel-dw2
- agi-kq4
- sci-kq5
- scumm-monkey2
- sci-sq3
- sci-sq5
- sci-sq6
- agos-waxworks

(not a complete list)

**Comment by GandalfTheWhite80** [comment]
BTW: Im working on the icons - maybe I will make an PR for them.
