### ISSUE TITLE
Icon update glk-sorcerer and glk-spellbreaker

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#180]
[glk-sorcerer.zip](https://github.com/scummvm/scummvm-icons/files/8303784/glk-sorcerer.zip)
![glk-sorcerer](https://user-images.githubusercontent.com/61733979/158988672-202d0034-1287-43fd-a30e-b9998f01907d.png)
[glk-spellbreaker.zip](https://github.com/scummvm/scummvm-icons/files/8303786/glk-spellbreaker.zip)
![glk-spellbreaker](https://user-images.githubusercontent.com/61733979/158988683-716e88f1-680c-4057-bb80-f13e25a50292.png)

**Comment by GandalfTheWhite80** [comment]
Updated :-)
