### ISSUE TITLE
glk-questforexcalibur icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#181]
[glk-questforexcalibur.zip](https://github.com/scummvm/scummvm-icons/files/8304266/glk-questforexcalibur.zip)
![glk-questforexcalibur](https://user-images.githubusercontent.com/61733979/158999799-281ebf1a-54f1-4739-8273-3bbba0c04112.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
