### ISSUE TITLE
glk-plunderedhearts icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#182]
[glk-plunderedhearts.zip](https://github.com/scummvm/scummvm-icons/files/8308558/glk-plunderedhearts.zip)
![glk-plunderedhearts](https://user-images.githubusercontent.com/61733979/159106398-c3142da5-7ccc-46de-8d79-14a73fd4a0c0.png)

**Comment by GandalfTheWhite80** [comment]
added thx!
