### ISSUE TITLE
Icon updates glk-adventurequest and glk-plunderedhearts

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#185]
Sorry about the hassle.

[glk-adventurequest.zip](https://github.com/scummvm/scummvm-icons/files/8311004/glk-adventurequest.zip)
![glk-adventurequest](https://user-images.githubusercontent.com/61733979/159157932-052b4f7e-b1d3-459e-9ee4-3dd4c3687e32.png)
[glk-plunderedhearts.zip](https://github.com/scummvm/scummvm-icons/files/8311023/glk-plunderedhearts.zip)
![glk-plunderedhearts](https://user-images.githubusercontent.com/61733979/159158070-c6487f8d-46f0-45ae-bb2e-f12a0a08b018.png)

**Comment by GandalfTheWhite80** [comment]
no problem - updated the 2 icons.
