### ISSUE TITLE
hypno-sinistersix icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#189]
[hypno-sinistersix.zip](https://github.com/scummvm/scummvm-icons/files/8337559/hypno-sinistersix.zip)
![hypno-sinistersix](https://user-images.githubusercontent.com/61733979/159820946-8ae65eb7-b6c3-4053-8a33-404f83ea2ae9.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx.
