### ISSUE TITLE
glk-wishbringer icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#191]
[glk-wishbringer.zip](https://github.com/scummvm/scummvm-icons/files/8355240/glk-wishbringer.zip)
![glk-wishbringer](https://user-images.githubusercontent.com/61733979/160236803-d135237c-dbe0-4d01-8215-e24a241f9583.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
