### ISSUE TITLE
ags-sqinc icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#192]
[ags-sqinc.zip](https://github.com/scummvm/scummvm-icons/files/8355302/ags-sqinc.zip)
![ags-sqinc](https://user-images.githubusercontent.com/61733979/160237775-ed234030-26c3-4a90-84c9-882b14af1972.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!

**Comment by GandalfTheWhite80** [comment]
PS size was 515x515 - uploaded a version with 512x512px :-)
