### ISSUE TITLE
glk-seastalker icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#194]
[glk-seastalker.zip](https://github.com/scummvm/scummvm-icons/files/8359177/glk-seastalker.zip)
![glk-seastalker](https://user-images.githubusercontent.com/61733979/160314956-dfbdda2a-9595-4ede-b924-70ae34c057cd.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx again!
