### ISSUE TITLE
glk-ootopos icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#196]
[glk-ootopos.zip](https://github.com/scummvm/scummvm-icons/files/8361962/glk-ootopos.zip)
![glk-ootopos](https://user-images.githubusercontent.com/61733979/160381898-79888150-08cd-4b7e-99ff-abe5a27b24c7.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx again!
