### ISSUE TITLE
glk-questforexcalibur icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#198]
[glk-questforexcalibur.zip](https://github.com/scummvm/scummvm-icons/files/8369624/glk-questforexcalibur.zip)
![glk-questforexcalibur](https://user-images.githubusercontent.com/61733979/160571817-eb9ca1dd-6361-4cf5-baf0-0425e451f92c.png)

**Comment by GandalfTheWhite80** [comment]
updated the icon :-)
