### ISSUE TITLE
glk-scottsampler icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#199]
[glk-scottsampler.zip](https://github.com/scummvm/scummvm-icons/files/8377619/glk-scottsampler.zip)
![glk-scottsampler](https://user-images.githubusercontent.com/61733979/160765549-88a5a969-fed2-4c98-97e0-32d26a76bbee.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx.
