### ISSUE TITLE
Ms Astro Chicken - icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#20]
[sci-ms-astro-chicken.zip](https://github.com/scummvm/scummvm-icons/files/5191986/sci-ms-astro-chicken.zip)
![sci-ms-astro-chicken](https://user-images.githubusercontent.com/61733979/92541914-6c5b5900-f29b-11ea-95a0-05a20dbaaf3b.png)

**Comment by SupSuper** [comment]
In the future, please use the IDs as listed in the Table of Contents (eg. `sci-astrochicken.png`)

**Comment by Tucky27** [comment]
Icon was for 
sci | msastrochicken | Ms. Astro Chicken

not Astro Chicken

**Comment by SupSuper** [comment]
Nice catch, fixed.
