### ISSUE TITLE
glk-talisman icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#204]
[glk-talisman.zip](https://github.com/scummvm/scummvm-icons/files/8401579/glk-talisman.zip)
![glk-talisman](https://user-images.githubusercontent.com/61733979/161361066-a3b393a6-d4dc-49fa-9c9c-9bb02f76a7a7.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
