### ISSUE TITLE
glk-crimsoncrown icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#206]
[glk-crimsoncrown.zip](https://github.com/scummvm/scummvm-icons/files/8404580/glk-crimsoncrown.zip)
![glk-crimsoncrown](https://user-images.githubusercontent.com/61733979/161430168-91091413-b956-4807-975c-5035b37cfe00.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
