### ISSUE TITLE
glk-hhgttg icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#209]
[glk-hhgttg.zip](https://github.com/scummvm/scummvm-icons/files/8406592/glk-hhgttg.zip)
![glk-hhgttg](https://user-images.githubusercontent.com/61733979/161471591-40e78ac1-7cc2-4c40-be3c-3a749e8edd13.png)

**Comment by GandalfTheWhite80** [comment]
Updated - Thx!
