### ISSUE TITLE
glk-nordbert icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#210]
[glk-nordbert.zip](https://github.com/scummvm/scummvm-icons/files/8406716/glk-nordbert.zip)
![glk-nordbert](https://user-images.githubusercontent.com/61733979/161474374-f40764fc-b66b-4b99-af1d-fc0f3b0a7a8e.png)

**Comment by GandalfTheWhite80** [comment]
Updated - Thx!
