### ISSUE TITLE
glk-planetfall icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#216]
[glk-planetfall.zip](https://github.com/scummvm/scummvm-icons/files/8478019/glk-planetfall.zip)
![glk-planetfall](https://user-images.githubusercontent.com/61733979/163095929-38903ffb-af7b-479e-9bc4-11a0ed2ef1f3.png)

**Comment by GandalfTheWhite80** [comment]
updated - Thx!
