### ISSUE TITLE
glk-hollywoodhijinx icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#218]
[glk-hollywoodhijinx.zip](https://github.com/scummvm/scummvm-icons/files/8486210/glk-hollywoodhijinx.zip)
![glk-hollywoodhijinx](https://user-images.githubusercontent.com/61733979/163313123-2ec63bdf-7f13-46a2-b343-a431572cede4.png)

**Comment by GandalfTheWhite80** [comment]
updated - THX!
