### ISSUE TITLE
glk-crimsoncrown icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#219]
[glk-crimsoncrown.zip](https://github.com/scummvm/scummvm-icons/files/8489446/glk-crimsoncrown.zip)
![glk-crimsoncrown](https://user-images.githubusercontent.com/61733979/163398999-edf0edc4-4f11-4245-9095-b0845316aeaa.png)

**Comment by GandalfTheWhite80** [comment]
updated - THX!
