### ISSUE TITLE
Updated icon for Scumm-SPY Fox 3-Operation Ozone

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#22]
[Scumm-SPY Fox 3-Operation Ozone.zip](https://github.com/scummvm/scummvm-icons/files/5193774/Scumm-SPY.Fox.3-Operation.Ozone.zip)
![Scumm-SPY Fox 3-Operation Ozone](https://user-images.githubusercontent.com/61733979/92575336-4c985500-f2dc-11ea-988d-d4ca7ca8f64b.png)

**Comment by Tucky27** [comment]
I decided to update this one as I noticed a few things that needed fixing. Hope you don't mind.

**Comment by SupSuper** [comment]
That's fine.
