### ISSUE TITLE
glk-borderzone icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#221]
[glk-borderzone.zip](https://github.com/scummvm/scummvm-icons/files/8488675/glk-borderzone.zip)
![glk-borderzone](https://user-images.githubusercontent.com/61733979/163379826-b81f2ba1-635a-4de8-ad4d-88b320eea6dc.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx
