### ISSUE TITLE
glk-shogun icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#222]
The original one wasn't so good on a dark grey background
[glk-shogun.zip](https://github.com/scummvm/scummvm-icons/files/8511525/glk-shogun.zip)
![glk-shogun](https://user-images.githubusercontent.com/61733979/163969322-99e671cf-91ca-4ecd-912c-96afd88f5099.png)

**Comment by GandalfTheWhite80** [comment]
updated the icon - thx
