### ISSUE TITLE
glk-moonmist icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#224]
[glk-moonmist.zip](https://github.com/scummvm/scummvm-icons/files/8516161/glk-moonmist.zip)
![glk-moonmist](https://user-images.githubusercontent.com/61733979/164086539-63b876ea-a541-4885-89a0-87875eba39f5.png)

**Comment by GandalfTheWhite80** [comment]
The icon is not 512x512 (it is 600x599?)

**Comment by Tucky27** [comment]
> The icon is not 512x512 (it is 600x599?)

I'm not sure how that happened. It was originally 512x512. I'll upload a new one.

**Comment by Tucky27** [comment]
New one should be fine now.

**Comment by GandalfTheWhite80** [comment]
added - Thx
