### ISSUE TITLE
glk-bureaucracy icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#227]
[glk-bureaucracy.zip](https://github.com/scummvm/scummvm-icons/files/8537085/glk-bureaucracy.zip)
![glk-bureaucracy](https://user-images.githubusercontent.com/61733979/164606399-7324cc56-6490-42a1-b22c-1fc71ac2cc56.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
