### ISSUE TITLE
glk-lurkinghorror icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#228]
[glk-lurkinghorror.zip](https://github.com/scummvm/scummvm-icons/files/8545818/glk-lurkinghorror.zip)
![glk-lurkinghorror](https://user-images.githubusercontent.com/61733979/164862407-f32e9ce7-e493-444f-9862-2def44fc20f0.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
