### ISSUE TITLE
glk-adventurequest & glk-dungeonadv icon update 

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#230]
[glk-adventurequest.zip](https://github.com/scummvm/scummvm-icons/files/8545946/glk-adventurequest.zip)
![glk-adventurequest](https://user-images.githubusercontent.com/61733979/164865839-7e6a822a-7148-4e8b-9f67-02d8fe75074e.png)
[glk-dungeonadv.zip](https://github.com/scummvm/scummvm-icons/files/8545947/glk-dungeonadv.zip)
![glk-dungeonadv](https://user-images.githubusercontent.com/61733979/164865865-135232bd-4010-46ec-b9e9-6e234e5c759b.png)

**Comment by GandalfTheWhite80** [comment]
updated - Thx!
