### ISSUE TITLE
glk-infidel icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#231]
[glk-infidel.zip](https://github.com/scummvm/scummvm-icons/files/8546047/glk-infidel.zip)
![glk-infidel](https://user-images.githubusercontent.com/61733979/164873025-922cdbd9-fb6f-49d7-9eca-7acdf03c69f0.png)

**Comment by GandalfTheWhite80** [comment]
Updated - Thx!
