### ISSUE TITLE
glk-cutthroats icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#232]
[glk-cutthroats.zip](https://github.com/scummvm/scummvm-icons/files/8546238/glk-cutthroats.zip)
![glk-cutthroats](https://user-images.githubusercontent.com/61733979/164878516-800e4b1e-70cb-441b-bd5f-e1cceb5e11f2.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
