### ISSUE TITLE
glk-infocomsampler 1&2 icons

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#235]
[glk-infocomsampler1&2.zip](https://github.com/scummvm/scummvm-icons/files/8554540/glk-infocomsampler1.2.zip)
![glk-infocomsampler1](https://user-images.githubusercontent.com/61733979/165090010-b323a8dd-16f1-4d0e-85f8-a6f85c76f60c.png)
![glk-infocomsampler2](https://user-images.githubusercontent.com/61733979/165089958-faf98499-5e75-4212-8bdd-69870ce5f282.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
