### ISSUE TITLE
ultima-martiandreams icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#240]
[ultima-martiandreams.zip](https://github.com/scummvm/scummvm-icons/files/8668667/ultima-martiandreams.zip)
![ultima-martiandreams](https://user-images.githubusercontent.com/61733979/167819702-393f9afc-f649-46a7-9544-ee6d6cf21295.png)

**Comment by Tucky27** [comment]
This is the game Worlds of Ultima: Martian Dreams.

**Comment by GandalfTheWhite80** [comment]
added - Thx
