### ISSUE TITLE
sci-freddypharkas icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#242]
[sci-freddypharkas.zip](https://github.com/scummvm/scummvm-icons/files/8804765/sci-freddypharkas.zip)
![sci-freddypharkas](https://user-images.githubusercontent.com/61733979/171165092-27d30404-0cd6-4246-870e-9ab0ef91b006.png)

**Comment by GandalfTheWhite80** [comment]
updated - Thx!
