### ISSUE TITLE
Mixed-Up Mother Goose EGA (mothergoose) duplicated for VGA (mothergoose256)

### ISSUE THREAD

**Issue by Thunderforge** [scummvm/scummvm-icons#244]
There are four versions of Mixed-up Mother Goose:

| Year  | Name | Short Name | Engine | Graphics Mode
| ------------- | ------------- | ------------- | ------------- |------------- |
| 1987 | Mixed-Up Mother Goose | `mothergoose` | AGI | |
| 1990 | Mixed-Up Mother Goose | `mothergoose` | SCI | EGA |
| 1991 | Mixed-Up Mother Goose | `mothergoose256` | SCI | VGA |
| 1995 | Mixed-Up Mother Goose Deluxe | `mothergoosehires` | SCI | SVGA |

Mixed Up Mother Goose - 256 colors version (`mothergoose256`) has [this icon](https://github.com/scummvm/scummvm-icons/blob/2b287b748a566dcfc1df34d1af49c02992e89024/icons/sci-mothergoose256.png), which is identical to [this icon](https://github.com/scummvm/scummvm-icons/blob/master/icons/sci-mothergoose.png) for the EGA version (`mothergoose`). 

<img width="513" alt="image" src="https://user-images.githubusercontent.com/6200170/173202155-eaf41c39-260b-4b42-bede-0c08b0fbd384.png">

However, the scene in question does not appear in the VGA version. Instead, the title screen looks like this

![mothergoose256-title](https://user-images.githubusercontent.com/6200170/173202020-0e5a4549-90f4-46c5-95db-a1c4a8fd1fff.png)

And the closest thing we get in-game to the icon shown is this image where the player character (not Mother Goose) flies on the goose.

![mothergoose256-ingame](https://user-images.githubusercontent.com/6200170/173202021-c26a3f37-dca5-419d-a714-e8c85b333ad1.png)

The icon for `mothergoose256` should instead be changed to look closer to the title screen, or otherwise use box art.

**Comment by GandalfTheWhite80** [comment]
Ok updated the agi version - Thx @Tucky27 !!!
