### ISSUE TITLE
scumm-spyfox icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#245]
[scumm-spyfox.zip](https://github.com/scummvm/scummvm-icons/files/8897541/scumm-spyfox.zip)
![scumm-spyfox](https://user-images.githubusercontent.com/61733979/173520576-cd594bd7-b97d-404e-a3d9-a8064e600238.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
