### ISSUE TITLE
kyra-The Legend of Kyrandia games icons

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#25]
[Kyrandia Games.zip](https://github.com/scummvm/scummvm-icons/files/5205806/Kyrandia.Games.zip)
![kyra-The Legend of Kyrandia](https://user-images.githubusercontent.com/61733979/92856984-2ee7fe80-f448-11ea-907b-ca00446eafba.png)
![kyra - The Legend of Kyrandia - The Hand of Fate](https://user-images.githubusercontent.com/61733979/92856996-31e2ef00-f448-11ea-87aa-156bd65999b4.png)
![kyra-The Legend of Kyrandia - Malcolm's Revenge](https://user-images.githubusercontent.com/61733979/92857002-33acb280-f448-11ea-8ed8-8053033fa6a6.png)

**Comment by SupSuper** [comment]
The Kyrandia 1 icon is pretty blurry, couldn't find a better scan?

**Comment by Tucky27** [comment]
I'll work on it some more and upload a new one.

**Comment by Tucky27** [comment]
I've updated the Kyrandia 1 icon
