### ISSUE TITLE
scumm-mustard icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#250]
[scumm-mustard.zip](https://github.com/scummvm/scummvm-icons/files/8905474/scumm-mustard.zip)
![scumm-mustard](https://user-images.githubusercontent.com/61733979/173731303-261dd22d-3278-4ccf-a8b1-d05c4f4e6f5d.png)

**Comment by GandalfTheWhite80** [comment]
Updated the icon - Thx!
