### ISSUE TITLE
SVG for TI-99/4A Platform

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#252]
[TI-99-4A.zip](https://github.com/scummvm/scummvm-icons/files/9034292/TI-99-4A.zip)
![TI-99-4A](https://user-images.githubusercontent.com/61733979/177030781-590d764d-0540-44cd-99eb-aaa15b600e23.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
