### ISSUE TITLE
scumm-puttsfunshop icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#255]
[scumm-puttsfunshop.zip](https://github.com/scummvm/scummvm-icons/files/9036770/scumm-puttsfunshop.zip)
![scumm-puttsfunshop](https://user-images.githubusercontent.com/61733979/177092300-451f99e4-dcd9-418a-877b-7a9f3122dc32.png)

**Comment by GandalfTheWhite80** [comment]
added - thx!
