### ISSUE TITLE
sci-mothergoosehires icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#257]
[sci-mothergoosehires.zip](https://github.com/scummvm/scummvm-icons/files/9039101/sci-mothergoosehires.zip)
![sci-mothergoosehires](https://user-images.githubusercontent.com/61733979/177148170-a17047d5-a8b1-4657-9bbc-809cabedcae0.png)

**Comment by GandalfTheWhite80** [comment]
updated - thx!
