### ISSUE TITLE
agi-mixedup icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#258]
[agi-mixedup.zip](https://github.com/scummvm/scummvm-icons/files/9039724/agi-mixedup.zip)
![agi-mixedup](https://user-images.githubusercontent.com/61733979/177162577-887fbba7-aa83-4ea1-92ec-7455257e04dd.png)

**Comment by GandalfTheWhite80** [comment]
updated - thx!
