### ISSUE TITLE
sci-cnick-lsl icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#259]
[sci-cnick-lsl.zip](https://github.com/scummvm/scummvm-icons/files/9051081/sci-cnick-lsl.zip)
![sci-cnick-lsl](https://user-images.githubusercontent.com/61733979/177457682-5bfa8023-1a2c-4442-a92d-2eabcdeef088.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
