### ISSUE TITLE
sci-cnick-sq icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#260]
[sci-cnick-sq.zip](https://github.com/scummvm/scummvm-icons/files/9051118/sci-cnick-sq.zip)
![sci-cnick-sq](https://user-images.githubusercontent.com/61733979/177458862-f8d6a559-e6e2-496b-b144-25b3bdb3c2c3.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
