### ISSUE TITLE
Add icons for all currently supported games for children

### ISSUE THREAD

**Issue by Thunderforge** [scummvm/scummvm-icons#262]
While many users will appreciate the icon-based grid view, children especially will appreciate it since they may not yet have learned how to read. Therefore, I think we should prioritize adding icons for games that are targeted for them.

The ones that we are currently missing are (sorted by priority based on how easy it is to obtain)

### Available for sale on Steam — High Priority

Since Steam is the most popular digital storefront for games, it's likely to have the most number of users owning these games.

- [x] *Big Thinkers! 1st Grade* (`scumm-thinker1`)
- [x] *Big Thinkers! Kindergarten* (`scumm-thinkerk`)
- [x] *Freddi Fish and Luther's Water Worries* (`scumm-water`)
- [x] *Pajama Sam's Sock Works* (`scumm-socks`)

### Available for sale on macOS/iOS/Android App Stores — Medium Priority

Fewer users will own these games than the Steam games because they are only available for those in certain ecosystems.

- [x] *Aesop's Fables: The Tortoise and the Hare* (`mohawk-tortoise`)
- [x] *Arthur's Birthday* (`mohawk-arthurbday`)
- [x] *Daniel in the Lions' Den* (`mohawk-daniel`)
- [x] *Harry and the Haunted House* (`mohawk-harryhh`)
- [x] *Just Grandma and Me* (`mohawk-grandma`)
- [x] *Little Monster at School* (`mohawk-lilmonster`)
- [x] *Ruff's Bone* (`mohawk-ruff`)
- [x] *Sheila Rae, the Brave* (`mohawk-sheila`)
- [x] *Stellaluna* (`mohawk-stellaluna`)
- [x] *The Berenstain Bears Get in a Fight* (`mohawk-bearfight`)
- [x] *The Berenstain Bears In The Dark* (`mohawk-beardark`)
- [x] *The New Kid on the Block* (`mohawk-newkid`)
- [x] *The Story of Creation* (`mohawk-create`)

### Not available for sale digitally — Low Priority

Since these games are not available digitally, the fewest number of users will have these games because they will need access to the original physical media.

- [x] *Dr. Seuss's ABC* (`mohawk-seussabc`)
- [x] *Green Eggs and Ham* (`mohawk-greeneggs`)
- [x] *Gregory and the Hot Air Balloon* (`composer-gregory`)
- [x] *Hades Challenge* (`hadesch-hadesch`)
- [x] *Slater & Charlie Go Camping* (`sci-slater`)

**Comment by GandalfTheWhite80** [comment]
I do have an icon for "The Story of Creation (create)" - but I don't know the engine :-(

**Comment by Thunderforge** [comment]
@GandalfTheWhite80 The engine is `mohawk`.

**Comment by GandalfTheWhite80** [comment]
added "Gregory" :-)

**Comment by Thunderforge** [comment]
Looks like that's all of the icons we need. Thanks everyone!
