### ISSUE TITLE
groovie-clandestiny icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#263]
[groovie-clandestiny.zip](https://github.com/scummvm/scummvm-icons/files/9078328/groovie-clandestiny.zip)
![groovie-clandestiny](https://user-images.githubusercontent.com/61733979/178129376-10f0ddd0-e717-4c09-a2d6-c37b86cc7e36.png)

**Comment by GandalfTheWhite80** [comment]
added - thx.
