### ISSUE TITLE
sci-cnick-longbow icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#264]
[sci-cnick-longbow.zip](https://github.com/scummvm/scummvm-icons/files/9078323/sci-cnick-longbow.zip)
![sci-cnick-longbow](https://user-images.githubusercontent.com/61733979/178129182-a9a8f95f-83d1-463a-97b6-55b2131e6833.png)

**Comment by GandalfTheWhite80** [comment]
added - thx.
