### ISSUE TITLE
mohawk-harryhh icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#274]
[mohawk-harryhh.zip](https://github.com/scummvm/scummvm-icons/files/9102114/mohawk-harryhh.zip)
![mohawk-harryhh](https://user-images.githubusercontent.com/61733979/178734463-1e535e65-6f7f-4d0d-b7d9-dafa5daafdca.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
