### ISSUE TITLE
mohawk-grandma icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#275]
[mohawk-grandma.zip](https://github.com/scummvm/scummvm-icons/files/9102419/mohawk-grandma.zip)
![mohawk-grandma](https://user-images.githubusercontent.com/61733979/178741019-95c397ce-e21e-4614-b2b1-8aa3cb177bc9.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx!
