### ISSUE TITLE
SVG for SCI Engine

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#283]
[SCI-v2.zip](https://github.com/scummvm/scummvm-icons/files/9136713/SCI-v2.zip)
![SCI-Engine](https://user-images.githubusercontent.com/61733979/179644605-7a230548-67bd-471d-9207-8f07d955c9fc.png)

**Comment by GandalfTheWhite80** [comment]
Are you sure about the blur filter?

**Comment by Tucky27** [comment]
> Are you sure about the blur filter?

This one is fine as is.

**Comment by GandalfTheWhite80** [comment]
updated - Thx!
