### ISSUE TITLE
ags-primordia icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#290]
[ags-primordia.zip](https://github.com/scummvm/scummvm-icons/files/9185150/ags-primordia.zip)
![ags-primordia](https://user-images.githubusercontent.com/61733979/180885488-91cc8424-8577-4a01-89f7-a6e49363b9f1.png)

**Comment by Thunderforge** [comment]
The figure at the bottom looks stretched out to me.

Can you confirm that this is the proportion that it's supposed to be? (If it is, that's fine, I just want to make sure there wasn't a mistake made during icon creation)

**Comment by Tucky27** [comment]
> The figure at the bottom looks horizontally stretched out to me.
> 
> Can you confirm that this is the proportion that it's supposed to be? (If it is, that's fine and no changes are needed, I just want to make sure there wasn't a mistake made during icon creation)

Your right it was stretched out. I found a better source and used that instead.

**Comment by GandalfTheWhite80** [comment]
added - Thx
