### ISSUE TITLE
mohawk-bearfight icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#291]
[mohawk-bearfight.zip](https://github.com/scummvm/scummvm-icons/files/9185357/mohawk-bearfight.zip)
![mohawk-bearfight](https://user-images.githubusercontent.com/61733979/180890613-34d7edaa-8376-4b71-b579-b72ff5469d0e.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx
