### ISSUE TITLE
sci-cnick-laurabow icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#292]
[sci-cnick-laurabow.zip](https://github.com/scummvm/scummvm-icons/files/9207409/sci-cnick-laurabow.zip)
![sci-cnick-laurabow](https://user-images.githubusercontent.com/61733979/181464079-a648c4a0-f3e4-4041-920e-8a98d1a99a95.png)

**Comment by GandalfTheWhite80** [comment]
added - thx
