### ISSUE TITLE
mohawk-beardark icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#297]
[mohawk-beardark.zip](https://github.com/scummvm/scummvm-icons/files/9226164/mohawk-beardark.zip)
![mohawk-beardark](https://user-images.githubusercontent.com/61733979/181909448-2d0bd7c2-eebe-4d98-8285-0aa57bccae20.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx
