### ISSUE TITLE
mohawk-greeneggs icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#298]
[mohawk-greeneggs.zip](https://github.com/scummvm/scummvm-icons/files/9226220/mohawk-greeneggs.zip)
![mohawk-greeneggs](https://user-images.githubusercontent.com/61733979/181910486-16a43241-2441-4bbd-9d81-ed47ee4342e8.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx
