### ISSUE TITLE
mohawk-seussabc icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#299]
[mohawk-seussabc.zip](https://github.com/scummvm/scummvm-icons/files/9226066/mohawk-seussabc.zip)
![mohawk-seussabc](https://user-images.githubusercontent.com/61733979/181908189-b6a95b63-4ebf-48e6-a66a-7561005ce166.png)

**Comment by GandalfTheWhite80** [comment]
added - Thx
