### ISSUE TITLE
mohawk-greeneggs icon update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#301]
[mohawk-greeneggs.zip](https://github.com/scummvm/scummvm-icons/files/9237497/mohawk-greeneggs.zip)
![mohawk-greeneggs](https://user-images.githubusercontent.com/61733979/182249271-fbc55da8-1012-413a-a2c0-b57652409a81.png)

**Comment by Thunderforge** [comment]
Updated, thank you!
