### ISSUE TITLE
ultima-thesavageempire icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#302]
[ultima-thesavageempire.zip](https://github.com/scummvm/scummvm-icons/files/9237931/ultima-thesavageempire.zip)
![ultima-thesavageempire](https://user-images.githubusercontent.com/61733979/182261757-12923dde-ef45-4c07-83ef-e8a98ca709f6.png)

**Comment by Thunderforge** [comment]
Added, thank you!
