### ISSUE TITLE
Added icons for selected Adventure Game Studio's Games (+ Bonus icons)

### ISSUE THREAD

**Issue by DavidAriyan** [scummvm/scummvm-icons#303]
The Scummvm GUI finally released. I've been so excited about this. Wanna see my favorites classic games on scummvm with it's cover art displayed is what I always looking for.
The scummvm's games library is HUGE. And the icons in the packs released are not available for all games off course. Many lesser known games still have their icons blank. 
So i decided to ask the developer via email. And thanks to him, I finally figure it out how to make my custom icons and i want to submit it for scummvm too if possible.

The source of all the icons is mainly: google search.
I googled them for majority of them. Some are in game screenshot, and some are pure custom.
I used the image enhancer app for each of them.
Doing some color corrections and some editing here and there. I've always avoid make the icons looks  the same as the source.

A link to the pack:
[gui-icons-ags.zip](https://github.com/scummvm/scummvm-icons/files/9302122/gui-icons-ags.zip)

I'll try add more icons when i found a game interesting.
I also added non AGS games icons because again for my personal taste.
If some of them already available at scummvm official icons pack, then consider what available here is the alternative version.

Note: to use the icon pack in scummvm, rename the zip to dat : gui-icons-ags.dat
And place them in the icon pack path you set for the scummvm.

There's a typo for the game icon: ags-therapods
It should be rename to: ags-theropods

This is the list of games icon that's in the zip in alphabetical order according to the icons name (since they're named differently than the actual game's name):

1. 46 Memory Lane
2. A Date In The Park
3. AeroNuts
4. A Landlord's Dream
5. All The Way Down
6. Almost Blue
7. A Second Face
8. The Black Cauldron Remake
9. Black Sect Remake
10. Chronicles Of Innsmouth
11. Detective Gallo
12. Downfall (2009)
13. Dustbowl
14. Enclosure (AGI games, i wrongly thought this as an AGS games because the similarity with 5 days a stranger)
15. Escape From The Chaotic City
16. The Man From The Fugue      State
17. Gemini Rue
18. GhostCatchers
19. Ghostdream
20. Him
21. I Am Jason
22. I Can't Sleep In Silence
23. Ice Station Zero
24. If On A Winter's Night: Four Travelers
25. I Want Out
26. Journey Home
27. La Croix Pan
28. Lamplight City
29. Metaphobia
30. Chronicles Of Innsmouth: Mountain Of Mandness
31. Mudlarks
32. My Burden To Keep
33. Neofeud
34. Nightmare Frames
35. When No Fear Was
36. Promordia
37. Rabbit Hill
38. Resonance
39. Rogue
40. Sepulchre
41. Skyfall
42. Spooks
43. Strangeland
44. Superego
45. Tea For Two
46. Technobabylon
47. Tales From The Outer Zone: Cyborg Seppuku
48: Tales From The Outer Zone:
The Goat Crone
49. The Awakening
50. The Cabin
51. The Cat Lady
52. The Infinity String
53. The Knobbly Crook
54. The Man That Only I Can See
55. The Marionette
56. Theropods
57. The Terrible Old Man
58. The Vacuum
59. Unavowed
60. Until I Have You
61. World Of Darkness Unbound: Prodigal
62. The Witch Lullaby

Bonus icons:
63.Blade Runner (With restored contents)
64. I Have No Mouth And I Must Scream

Change logs:
Update 10/08/2022:
- Removed previous icon pack.
- Reworked all the icons, adding rounded corners (so i think they're had some alpha/transparency now.) to add uniformity with the official scummvm icon packs,  and to meet the standard of nowadays tech world. Even your phone / computer screens are now have rounded corners.
- Resized all high res icons to 512x512px to meet the standard requirements.
- Removed already existing icons (like the panthom fellow), but still included Blade Runner & IHNMAIMS.
- Added 14 more new icons. 64 icons in total.
- Added stylized title text for icons that doesn't have it. (Like Detective Gallo, etc)
They're still some icons i liked to keep it have no text like Strangeland because personal liking.

**Comment by GandalfTheWhite80** [comment]
Thx a lot! I will have a closer look in the next days

**Comment by DavidAriyan** [comment]
> Thx a lot! I will have a closer look in the next days

You're welcome. Hope you could find your favorite games icon there.

**Comment by GandalfTheWhite80** [comment]
I have a few remarks/questions
- All icons have to be 512x512px 
- What is the source of this icons ? Have you created them all by yourself?

**Comment by DavidAriyan** [comment]
> I have a few remarks/questions
> 
> * All icons have to be 512x512px
> * What is the source of this icons ? Have you created them all by yourself?
> 
> icons already present
> 
> * saga-ihnm
> * bladerunner-bladerunner-final (src of image?)
> * ags-primordia
> * ags-phantomfellows vs. ags-thepantomfellows
> 
> icons without alpha (but should have)
> 
> * ags-bcremake
> * ags-detectivgallo
> * ags-dusbowl
> * ags-escapefromthechaoticcity
> * ags-geminirue (mmaybe)
> * ags-him
> * ags-icantsleep
> * ags-neofued
> * ags-nofear
> * ags-rabbithill
> * ags-sepulchre
> * ags-skyfall
> * ags-tftoz1
> * ags-tftoz2
> * ags-themanthatonlyicansee

Okey let me explain:
At first i got this idea to create the icons myself since it doesn't in official scummvm icon pack yet.
And i ask the developer via email and one of the team (Eugene) answer my question and explain to me how to create custom icons.
I'm surprised It's works on the GUI. And send him screenshot of it. He advised me to upload my custom icons to GitHub so maybe i can help other users who need it.

At first  i resized the icons to 512x512. Then i experiment a bit. Turns out the GUI works just fine with higher pixel icon.
So I decided to made the rest of them in higher pixels in order to keep quality.

The source is: google.
I googled them for majority of them. Some are in game screenshot, and some are pure custom.
I use image enhancer app in each of them.
Doing some color corrections and some editing here and there. So it won't looks the same as the source.

For the Blade Runner & Ihnmaims icon? I personally wanna look the game use that version of artworks so i decided to included them as well in the zip.

Icons without alpha? What is alpha meaning? I don't understand.
I like to make the icons different in each so it doesn't look boring. Some have Title text, some don't.

I like to use them for personal use.
So it's okay with me if it don't ended up on scummvm official icon packs.

**Comment by GandalfTheWhite80** [comment]
I was refering to an alpha transparency - https://de.wikipedia.org/wiki/Datei:PNG_transparency_demonstration_1.png

**Comment by DavidAriyan** [comment]
> I was refering to an alpha transparency - https://de.wikipedia.org/wiki/Datei:PNG_transparency_demonstration_1.png

I just edited already existing image and just doing some enhancement here and there. So adding alpa transparancy was not possible. Or i just don't bother do it. I just glad my games collection has icon displayed in the new GUI. 
I was exited.

**Comment by GandalfTheWhite80** [comment]
Nobody said that adding transparency is an "easy" way.

But the icons have to be 
- 512x512px
- should use alpha where appropriate

Have a look at:
https://github.com/scummvm/scummvm-icons

**Comment by DavidAriyan** [comment]
> Nobody said that adding transparency is an "easy" way.
> 
> But the icons have to be
> 
> * 512x512px
> * should use alpha where appropriate
> 
> Have a look at: https://github.com/scummvm/scummvm-icons

I'll fix it next time.
Maybe adding more icons and make them all 512x512px.

**Comment by Thunderforge** [comment]
Aside from the previous request for 512x512px and consistent alpha usage:

* Several icons have no text to identify the game (e.g. `asecondface`, `chroniclesofinnsmouth`, `detectivegallo`. It seems our existing icons all have text, so I think that should be added.
* `ioawn4t` and `sepulchre` come across as low-res images, particular in the words, I think due to the unclear boundary lines. I'm guessing it was sourced from the title screen. Contrast with `iamjason` and `rogue` which also use the retro art style but are very "clean" in terms of pixel boundaries. I wonder if there's a better image we can find for these game.
* `nofear` is an unreadable blur. I'm not sure how much we can do about it since it's probably the logo. Maybe making it take up slightly more space would help?

This might be a good time to revisit #85 and see if we can hammer out some guidelines on how to make icons (can you just google it, etc) as well as codify some unwritten rules (e.g. icons should have text).

**Comment by DavidAriyan** [comment]
> Aside from the previous request for 512x512px and consistent alpha usage:
> 
> * Several icons have no text to identify the game (e.g. `asecondface`, `chroniclesofinnsmouth`, `detectivegallo`. It seems our existing icons all have text, so I think that should be added.
> * `ioawn4t` and `sepulchre` come across as low-res images, particular in the words, I think due to the unclear boundary lines. I'm guessing it was sourced from the title screen. Contrast with `iamjason` and `rogue` which also use the retro art style but are very "clean" in terms of pixel boundaries. I wonder if there's a better image we can find for these game.
> * `nofear` is an unreadable blur. I'm not sure how much we can do about it since it's probably the logo. Maybe making it take up slightly more space would help?
> 
> This might be a good time to revisit #85 and see if we can hammer out some guidelines on how to make icons (can you just google it, etc) as well as codify some unwritten rules (e.g. icons should have text).

Yes, that's right. The title that have no text mainly because i personally because i found it better in that state... I wonder if other users could edit them and adding text in it.
Icons for : ioawn4t & spulchre is considerably in low res because i can't find better quality for them.
Spulchre icon just the title screen with removed sub menu. While ioawn4t has been heavily edited with different tone of colours than the original. 

Wait for it. I think I'm gonna update the .zip to change the icons 512x512 and adding rounded corners in them.

**Comment by tag2015** [comment]
Just a few tips

ioawn4t is available on steam, maybe you could reuse the title art from the store page?
https://cdn.akamai.steamstatic.com/steam/apps/1603980/header.jpg?t=1659987306

The same could be done for detective gallo, strangeland and others
https://cdn.akamai.steamstatic.com/steam/apps/556060/header.jpg?t=1652630924
https://cdn.akamai.steamstatic.com/steam/apps/1369520/header.jpg?t=1657774841
etc

IAMJASON is missing the "IAM"
https://gamejolt.com/games/iamjason/53523

**Comment by DavidAriyan** [comment]
> Just a few tips
> 
> ioawn4t is available on steam, maybe you could reuse the title art from the store page? https://cdn.akamai.steamstatic.com/steam/apps/1603980/header.jpg?t=1659987306
> 
> The same could be done for detective gallo, strangeland and others https://cdn.akamai.steamstatic.com/steam/apps/556060/header.jpg?t=1652630924 https://cdn.akamai.steamstatic.com/steam/apps/1369520/header.jpg?t=1657774841 etc
> 
> IAMJASON is missing the "IAM" https://gamejolt.com/games/iamjason/53523

Thank you for the tips. Those icons i already updated it. I added text title manually too.
Added new icons up to 64 in total.
Just few hours and the i ready to release it.

**Comment by GandalfTheWhite80** [comment]
Thx a lot (again) - If there is no objection I will hava a closer look later (maybe tomorrow or friday) and add some transparancy for the icons mentioned above. 

BTW It is easier to discuss this in the icons discord channel :-)

**Comment by GandalfTheWhite80** [comment]
PS I'm not so sure that your sources for example https://gamejolt.com/games/iamjason/53523 a useable as "fair usage" (as covers are/should be)

**Comment by DavidAriyan** [comment]
> PS I'm not so sure that your sources for example https://gamejolt.com/games/iamjason/53523 a useable as "fair usage" (as covers are/should be)
> 
> PPS @DavidAriyan could you pack a new zip and update your initial zip?

Okay I'll added it now.
Did i need to remove the previous zip?

**Comment by GandalfTheWhite80** [comment]
You need to edit your request / first comment and delete/upload the new zip

**Comment by DavidAriyan** [comment]
> You need to edit your request / first comment and delete/upload the new zip

Uploaded!
Have a look.

**Comment by DavidAriyan** [comment]
> PS I'm not so sure that your sources for example https://gamejolt.com/games/iamjason/53523 a useable as "fair usage" (as covers are/should be)
> 
> PPS @DavidAriyan could you pack a new zip and update your initial zip?

Honestly it's a screenshot from the actual game intro. I edited it in Lightroom.
I don't take any cover from gamejolt because it's doesn't match the square icon.
But sometimes I took from itch.io.

**Comment by DavidAriyan** [comment]
> Thx a lot (again) - If there is no objection I will hava a closer look later (maybe tomorrow or friday) and add some transparancy for the icons mentioned above.
> 
> BTW It is easier to discuss this in the icons discord channel :-)

Sadly I just can't talk in discord channel for scummvm. It need verification code from my phone number. I had entered my numbers so many times and didn't get the verification code. I wonder if this bug from dischord itself. 
So that's why I posted my custom icons here instead.

**Comment by DavidAriyan** [comment]
> Thx a lot (again) - If there is no objection I will hava a closer look later (maybe tomorrow or friday) and add some transparancy for the icons mentioned above.
> 
> BTW It is easier to discuss this in the icons discord channel :-)

Okey. Thank you in advance.

**Comment by GandalfTheWhite80** [comment]
Here are four (of the easier) icons I would add transparency

![ags-bcremake-v1](https://user-images.githubusercontent.com/71585967/183995073-62f89f76-dfce-49ad-a4a7-54049898b10a.png)
![ags-detectivegallo-v1](https://user-images.githubusercontent.com/71585967/183995080-3dc54d8b-cb3c-4a03-89f4-755eb90e5a20.png)
![ags-neofeud-v1](https://user-images.githubusercontent.com/71585967/183995089-af3e91ff-0a5d-4122-af65-014b887e3ff6.png)
![ags-therapods-v1](https://user-images.githubusercontent.com/71585967/183995099-432ccdbf-7aeb-402b-94c4-53b4188539c6.png)

**Comment by DavidAriyan** [comment]
That's look very good. 
I think this is suitable for icons with black background.
But some icons like theropods need that green background to give it a theme.

**Comment by DavidAriyan** [comment]
> Here are four (of the easier) icons I would add transparency (try it / view it with white / black background :-) )
> 
> ![ags-bcremake-v1](https://user-images.githubusercontent.com/71585967/183995073-62f89f76-dfce-49ad-a4a7-54049898b10a.png) ![ags-detectivegallo-v1](https://user-images.githubusercontent.com/71585967/183995080-3dc54d8b-cb3c-4a03-89f4-755eb90e5a20.png) ![ags-neofeud-v1](https://user-images.githubusercontent.com/71585967/183995089-af3e91ff-0a5d-4122-af65-014b887e3ff6.png) ![ags-therapods-v1](https://user-images.githubusercontent.com/71585967/183995099-432ccdbf-7aeb-402b-94c4-53b4188539c6.png)

They're looks so clean. What app / programs do you used.?
When it finish, could you uploaded it here or i have to update my icons pack again?
Don't be rush though.

**Comment by DavidAriyan** [comment]
> Thx a lot (again) - If there is no objection I will hava a closer look later (maybe tomorrow or friday) and add some transparancy for the icons mentioned above.
> 
> BTW It is easier to discuss this in the icons discord channel :-)

Can you help me to get a talk role there? I wonder if there's a way to bypass that annoying verification bug.

**Comment by GandalfTheWhite80** [comment]
No i'm just a normal user in discord. And I don't know if there is a way without verification.

I'm using gimp most of the time.

**Comment by DavidAriyan** [comment]
> Here are four (of the easier) icons I would add transparency (try it / view it with white / black background :-) )
> 
> ![ags-bcremake-v1](https://user-images.githubusercontent.com/71585967/183995073-62f89f76-dfce-49ad-a4a7-54049898b10a.png) ![ags-detectivegallo-v1](https://user-images.githubusercontent.com/71585967/183995080-3dc54d8b-cb3c-4a03-89f4-755eb90e5a20.png) ![ags-neofeud-v1](https://user-images.githubusercontent.com/71585967/183995089-af3e91ff-0a5d-4122-af65-014b887e3ff6.png) ![ags-therapods-v1](https://user-images.githubusercontent.com/71585967/183995099-432ccdbf-7aeb-402b-94c4-53b4188539c6.png)

I just made another typo. The theropods icon wrongly named therapods. I should update it again soon. But I'm having difficulty naming icons for games that i don't have. Usually i look for the game id in the scummvm UI. Can't find a list for gameid especially with lesser known games.

**Comment by DavidAriyan** [comment]
> No i'm just a normal user in discord. And I don't know if there is a way without verification.
> 
> I'm using gimp most of the time.

That's fine. Gimp for PC or phone?
I'm using various app on my phone to get the icons right. Including Autodesk sketchbook.
Glad I found the new app: ihancer to get my icons higher resolution and detailed.

**Comment by GandalfTheWhite80** [comment]
I had the same question not long ago

Ypu could try to find it here: https://www.scummvm.org/compatibility/

**Comment by DavidAriyan** [comment]
> I had the same question not long ago
> 
> Ypu could try to find it here: https://www.scummvm.org/compatibility/

Yeah, i remember that is the best place to get the id when I don't have the game.
Thanks gotta save it for offline reading.

**Comment by DavidAriyan** [comment]
> Gimp for PC, always editing images on a Desktop PC:-)
> 
> I had the same question not long ago
> 
> Ypu could try to find it here: https://www.scummvm.org/compatibility/

I don't have a PC for now.
I'm using my android for these editing works.
They're pretty good except i can't find good app for making decent transparency.

**Comment by DavidAriyan** [comment]
> Gimp for PC, always editing images on a Desktop PC:-)
> 
> I had the same question not long ago
> 
> Ypu could try to find it here: https://www.scummvm.org/compatibility/

Some games or newer ones do doesn't appear on the list, so like theropods here i ended up guessing the id using only the real title. Unfortunately not all games using their real title for the gameid. But I'll do my best to make the icons have the correct game id when possible.

**Comment by tag2015** [comment]
The complete list of identifiers for ags games is here
https://github.com/scummvm/scummvm/blob/master/engines/ags/detection_tables.h
supported games start at line 227

**Comment by DavidAriyan** [comment]
> The complete list of identifiers for ags games is here https://github.com/scummvm/scummvm/blob/master/engines/ags/detection_tables.h supported games start at line 227

That's very nice of you.
I saved this page too.
Thanks a lot. This will make making icons easier.
Fell free to help me complete the AGS icons task if you have time.

I'm interested in horror and adventure games mostly if i can find another hidden dark ags games, I'll make an icons for it. 
Scummvm team being works hard lately to made the GUI.

**Comment by Thunderforge** [comment]
> Some games or newer ones do doesn't appear on the list, so like theropods here i ended up guessing the id using only the real title. 

With the hundreds of games added through AGS and Wintermute and such, we do sadly have plenty of games missing (we've been talking about strategies to mitigate this, both nothing has really been planned). There's also a lot of games that we theoretically support, but haven't been tested.

If there are games you think should be on the list but aren't, feel free to share (it would be better in Discord, if you can get your login issues worked out).

**Comment by DavidAriyan** [comment]
We just need time and progress and hoping other user to want to submit their icons for games that doesn't have it. 

Talking about the game that deserves icons, i personally like game that have dark mystery and horror themed so when I see one i made icons for it.
Even when they are not playable yet on scummvm:
La Croix Pan, Ice Station Zero, wdu Prodigal, the cat lady, almost blue, all the way down, & strangeland are these game. Some of them crash, some in game but has very low fps.

For the discord, I'm not sure I'm ever gonna have a chance to talk there, because it's mainly discord' bugs. We'll see.

**Comment by DavidAriyan** [comment]
> > Some games or newer ones do doesn't appear on the list, so like theropods here i ended up guessing the id using only the real title.
> 
> With the hundreds of games added through AGS and Wintermute and such, we do sadly have plenty of games missing (we've been talking about strategies to mitigate this, both nothing has really been planned). There's also a lot of games that we theoretically support, but haven't been tested.
> 
> If there are games you think should be on the list but aren't, feel free to share (it would be better in Discord, if you can get your login issues worked out).

Something wrong with the GitHub. I can't upload any zip file to my first comment. I wonder what's wrong.

**Comment by GandalfTheWhite80** [comment]
Maybe we should stay ( for this issue) with the games you have provided in the current zip.

As we May have some discussions in discord   could you add a list as in 
https://github.com/scummvm/scummvm-icons/issues/261
to your issue?

I will add the first icons ( see discord history ) after running advdef on the pngs on monday :-)

**Comment by tag2015** [comment]
There's a small error in the archive, "Enclosure" is an AGI game, not an AGS game and should be named as such.

Regarding the icons, having an icon for every AGS game is clearly unfeasible.
Personally I think that it'd be nice to have icons for most/all commercial AGS games (which aren't too many).
For freeware games, it could be restricted to well-known games of a decent length, as there's not much point in having icons for games that are very amateurish or have a play length of a couple minutes (and there are a lot like that)

**Comment by DavidAriyan** [comment]
> There's a small error in the archive, "Enclosure" is an AGI game, not an AGS game and should be named as such.
> 
> Regarding the icons, having an icon for every AGS game is clearly unfeasible. Personally I think that it'd be nice to have icons for most/all commercial AGS games (which aren't too many). For freeware games, it could be restricted to well-known games of a decent length, as there's not much point in having icons for games that are very amateurish or have a play length of a couple minutes (and there are a lot like that)

Thanks for inform me about this. I thought is a ags game.

The point here is, making as much as icons for every game scummvm supported.  So less game having their icons in the GUI get blank. it just need time, and maybe need other users to freely submit their icons. As they will.

Beside, i like to make icons for gamea that i personally like. I mainly focused on horror themed games. I'm interested in dark, scary, mystery, suspense movies/ games since I was a kid.
So having to focused on commercial games that i didn't interested or don't have is not my priority. But i try my best. Again we need more contributers for scummvm GUI icons.
Let's hope there's more users willing to do this in their free time.
I planned to separate the AGS icons and non ags. But for now i just can't upload anything. Since there's an error with GitHub upload.

**Comment by tag2015** [comment]
> The point here is, making as much as icons for every game scummvm supported.

That's thousands of games...

> Not all freeware AGS games are ametuers. Take a look at Metaphobia for example.
> A Second Face, The Infinity Strings, The Knobbly Crook they are all epic adventure game with long hours gameplay.

I know, that's exactly what i meant. Prioritize games that are well known (metaphobia and TKC are even on steam), mostly because more people are going to play them in scummvm and use the relative icon.
It's also written in the icons guidelines:
"prioritize mainstream titles over minor fan games and tech demos"

I can't personally contribute icons as it's time consuming and I'm focusing on other tasks right now. However I'm compiling a list of AGS games that (in my opinion) are good candidates, if anybody wants to create the icons:
https://docs.google.com/spreadsheets/d/1dYTXGlSJSkQlR7mzGXbyJIXhMwuVMJfvgvEImQg13ZE/edit?usp=sharing
Just a start. I'll add more in the coming days

**Comment by DavidAriyan** [comment]
> > The point here is, making as much as icons for every game scummvm supported.
> 
> That's thousands of games...
> 
> > Not all freeware AGS games are ametuers. Take a look at Metaphobia for example.
> > A Second Face, The Infinity Strings, The Knobbly Crook they are all epic adventure game with long hours gameplay.
> 
> I know, that's exactly what i meant. Prioritize games that are well known (metaphobia and TKC are even on steam), mostly because more people are going to play them in scummvm and use the relative icon. It's also written in the icons guidelines: "prioritize mainstream titles over minor fan games and tech demos"
> 
> I can't personally contribute icons as it's time consuming and I'm focusing on other tasks right now. However I'm compiling a list of AGS games that (in my opinion) are good candidates, if anybody wants to create the icons: https://docs.google.com/spreadsheets/d/1dYTXGlSJSkQlR7mzGXbyJIXhMwuVMJfvgvEImQg13ZE/edit?usp=sharing Just a start. I'll add more in the coming days

Yeah i know about this. "prioritize mainstream titles over minor fan games and tech demos". Indie lesser known games that i had covered are all stand alone games and they are completable not just demo or fan version of already known games.
Many of them are available too on other site like itch.io & gamejolt. And about the game list, I'll try my best to keep it up with it. And Let's anyone join.
For now i just can't upload my zip file to GitHub. I don't know what to do. I have no idea how to do it.
All zip are below 25 MB. Still failed to upload. Do you have any thought?
