### ISSUE TITLE
Add icons for selected Adventure Game Studio's games + Bonus icons 

### ISSUE THREAD

**Issue by DavidAriyan** [scummvm/scummvm-icons#304]
The Scummvm GUI finally released. I've been so excited about this. Wanna see my favorites classic games on scummvm with it's cover art displayed is what I always looking for.
The scummvm's games library is HUGE. And the icons in the packs released are not available for all games off course. Many lesser known games still have their icons blank. 
So i decided to ask the developer via email. And thanks to him, I finally figure it out how to make my custom icons and i want to submit it for scummvm too if possible.

The main focused here to complete the icons for available games created with Adventure Game Studio's engine (AGS).

I've been big fans of adventure, mystery, horror games or movies so many icons here are based on my personal likings.

Many of these hidden gems works fine on scummvm, some crash, some of them have really low fps render them unplayable. But off course I still hope someday scummvm team will make them playable, like Blade Runner a game that i never thought will play on phone.

The source of all the icons is mainly: google search.
I googled them for majority of them. Some are in game screenshot, and some are pure custom.
I used the image enhancer app for each of them.
Doing some color corrections and some editing here and there. I've always avoid make the icons looks  the same as the source.

I'll try add more icons when i found a game interesting.
I also added non AGS games icons because again for my personal taste.
If some of them already available at scummvm official icons pack, then consider what available here is the alternative version.

Hope you'll like it.
Any feedbacks, comments, request, or even help to complete the ags icon packs. Because they're so many good hidden gem in that system.
I'll be appreciated.

Links to the pack:
AGS icons:
https://drive.google.com/file/d/1SIiAk2AK6emrjgC18beBCdx5v1KkCX7J/view?usp=drivesdk

Alternatives icons:
https://drive.google.com/file/d/1MZukhVt9f_AtkwlMHe7QxxL1-tUwYgm9/view?usp=drivesdk

What's in the box:
https://docs.google.com/spreadsheets/d/1gzgFx07wJML109hzcIAiSCO3ka0awQFjGm_2eB5hmyQ/edit?usp=drivesdk

Note: to use the icon pack in scummvm, rename the zip to dat example : gui-icons-ags.zip --> gui-icons-ags.dat
And place them in the icon pack path you set for the scummvm.
The alternative icons will immediately replace the icons available from the official scummvm icons pack, once you put them in the scummvm icon path you had set.
No need to unpack or change anything in the official scummvm icon packs.

Guides:
The complete list of identifiers for ags games is here
https://github.com/scummvm/scummvm/blob/master/engines/ags/detection_tables.h
supported games start at line 227

list of AGS games by @tag2015 that are good candidates, if anybody wants to create the icons:
https://docs.google.com/spreadsheets/d/1dYTXGlSJSkQlR7mzGXbyJIXhMwuVMJfvgvEImQg13ZE/edit?usp=sharing

Report me if you see any games that already have an icon in the scummvm's icons packs. I'll move my icons version to alternate icons. Because i just can't track every single icon. it's very time consuming. Beside i only make icon for the game that i like and worthy to have an icon.
You can try to request, if you find an interesting game (especially dark, mystery, & horror themed games) please let me know.

Change log:

21/08/2022
- Added more 40 game's icons. 105 AGS game's 
  icons in total.
- Slightly altered icons for "The Vacuum" to remove 
  the pointer.
- Completely new icon for "A Second Face: The Eye Of Geltz.
- Updated the spreadsheet off course.

17/08/2022
- Corrected game id name for few games.

16/08/2022
- All icons has been reworked/ redone to remove the rounded corners that unfit with the scummvm gui.
- Title has been added to several icons.
- Completely new icons for some games.
- Removed Blade Runner icon from the alternate icons pack (it''s now included in a new issue #305)
---
Done (added/uploaded to github)
- [x] 5 Days a Stranger / ags-5daysastranger
- [x] 6 Days a Sacrifice / ags-6daysasacrifice
- [x] 7 Days a Skeptic / ags-7daysaskeptic
- [x] 9 Hours to Dawn / ags-9hourstodawn
- [x] 46 Memory Lane / ags-46memorylane
- [x] A Christmas Nightmare / ags-achristmasnightmare
- [x] A Date In The Park / ags-adateinthepark
- [x] Aeronuts / ags-aeronuts
- [x] A Fragment of Her / ags-afragmentofher
- [x] A Landlord's Dream / ags-alandlordsdream
- [x] All The Way Down / ags-allthewaydown
- [x] Almost Blue / ags-almostblue
- [x] Archeos / ags-archeos
- [x] A Second Face / ags-asecondface
- [x] The Black Cauldron / ags-bcremake
- [x] Beyond Horizon / ags-beyondhorizon
- [x] Bitstream / ags-bitstream
- [x] Black Morph / ags-blackmorph
- [x] Black Sect / ags-blacksect1
- [x] Blooded Fields / ags-bloodedfields
- [x] Breakage / ags-breakage
- [x] Camp 1 / ags-camp1
- [x] The Charnel House Triology / ags-charnelhousetrilogy
- [x] Chronical Of Innsmouth / ags-chronicleofinnsmouth
- [x] Concurrence / ags-concurrence
- [x] Conspiracy: Below Zero / ags-conspiracybelowzero
- [x] Contact / ags-contact
- [x] Content / ags-content
- [x] Da New Guys / ags-danewguys
- [x] Detective Gallo / ags-detectivegallo
- [x] Downfall / ags-downfall2009
- [x] Dustbowl / ags-dustbowl
- [ ] Enclosure / ags-enclosure
- [x] Escape From The Chaotic City / ags-escapefromthechaoticcity
- [x] Fall / ags-fall
- [x] Football Game / ags-footballgame
- [x] The Man From The Fugue State / ags-fuguestate
- [x] Gemini Rue / ags-geminirue
- [x] GhostCatchers / ags-ghostcatchers
- [x] Ghostdream / ags-ghostdream
- [x] Heartland / ags-heartland
- [x] Him / ags-him
- [x] Hjarta / ags-hjarta
- [x] I Am Jason / ags-iamjason
- [x] I Can't Sleep In Silence / ags-icantsleep
- [x] Ice Station Zero / ags-icestationzero
- [x] In Bloom / ags-inbloom
- [x] If On A Winter's Night: Four Travellers / ags-ioawn4t
- [x] I Want Out! / ags-iwantout
- [x] Journey to Hell / ags-journeyhell
- [x] Journey Home / ags-journeyhome
- [x] The Knobbly Crook / ags-knobblycrook
- [x] La Croix Pan / ags-lacroixpan
- [x] Lamplight City / ags-lamplightcity
- [x] Lost Answers / ags-lostanswers
- [x] Lost In The Nightmare / ags-lostinthenightmare
- [x] Masked / ags-masked
- [x] Metaphobia / ags-metaphobia
- [x] Chronicle Of Innsmouth: Mountains Of Madness / ags-mountainsofmadness
- [x] Mudlarks / ags-mudlarks
- [x] My Burden To Keep / ags-myburdentokeep
- [x] My Father's Secret / ags-myfatherssecret
- [x] Neofeud / ags-neofeud
- [x] Neos Aires 2070 / ags-neosaires2070
- [x] Nightmare Frames / ags-nightmareframes
- [x] Where No Fear Was / ags-nofear
- [x] PatchWork / ags-patchwork
- [x] Primordia / ags-primordia
- [x] Rabbit Hill / ags-rabbithill
- [x] Reactor 09 / ags-reactor09
- [x] Resonance / ags-resonance
- [x] Rogue / ags-rogue
- [x] The Samaritan Paradox / ags-samaritan
- [x] Sepulchre / ags-sepulchre
- [x] Skumring / ags-skumring
- [x] Skyfall / ags-skyfall
- [x] Spooks / ags-spooks
- [x] Strangeland / ags-strangeland
- [x] Superego Chapter 0 / ags-superegoch0
- [x] A Tea For Two / ags-teafortwo
- [x] Technobabylon / ags-technobabylon
- [x] Tales From The Outer Zone: Cyborg Seppuku / ags-tftoz1
- [x] Tales From The Outer Zone: The Goat Crone / ags-tftoz2
- [x] Tales From The Outer Zone:  The Construction / ags-tftoz3
- [x] Tales From The Outer Zone:  The Goat Crone / ags-tftoz4
- [x] The Awekening / ags-theawakening
- [x] The Cabin / ags-thecabin
- [x] The Cat Lady / ags-thecatlady
- [x] The Experiment - Part 1: The Laboratory / ags-theexperimentp1
- [x] The Experiment - Part 1: Menacing Darkness / ags-theexperimentp2
- [x] The Infinity String / ags-theinfinitystring
- [x] The Man That Only I Can See / ags-themanisee
- [x]  The Marionette / ags-themarionette
- [x] The Oven / ags-theoven
- [x] The Reaper / ags-thereaper
- [x] The Rebirth / ags-therebirth
- [x]  Theropods / ags-therapods
- [x] The Shaft / ags-theshaft
- [x] The Terrible Old Man / ags-theterribleoldman
- [x] The Vacuum / ags-thevacuum
- [x] Trilby's Notes / ags-trilbysnote
- [x] Twelve Thirteen - Special Edition / ags-twelvethirteense
- [x] Unavowed / ags-unavowed
- [x] Unbound / ags-unbound
- [x] Untill I Have You / ags-untilihaveyou
- [x] Prodigal / ags-wduprodigal
- [x] The Witch's Lullaby / ags-witchlullaby

**Comment by GandalfTheWhite80** [comment]
1. Should we create a task list 
2. We have the toc.md 

I was referring to a task list we could ''check" wenn an icon is added

**Comment by DavidAriyan** [comment]
> 1. Should we create a task list
> 2. We have the toc.md
> 
> I was referring to a task list we could ''check" wenn an icon is added.
> 
> Peronally, why close the old issue
1. If should, yes. I let you do the honors. I don't know how to make task list.

Why I close the issue #303?
It was a mistake. Because i can't upload any changes there. So i created new issue and close the old one. But now it's happening again. I can't upload new zip. So i ended up adding google drive link for new icons

**Comment by GandalfTheWhite80** [comment]
A few things for this Issue
- pls don't add/mix with non ags games -> make separate issues if you want to add/update other icons
- Add "new" games to the task list carefully. If not we will have a never ending issue. Maybe it is better to focus on the icons you provided and discuss them (if needed) in our discord channel

**Comment by DavidAriyan** [comment]
> A few things for this Issue
> 
> * pls don't add/mix with non ags games -> make separate issues if you want to add/update other icons
> * Add "new" games to the task list carefully. If not we will have a never ending issue. Maybe it is better to focus on the icons you provided and discuss them (if needed) in our discord channel

But it's because i liked those games (the non AGS and i like to add icons for own use. Since several of them not available yet on the official scummvm icon, why not i shared those icons here. 
I just can't make those icons as separate issues, because they are combinations of differents engine.
Please understand.

**Comment by GandalfTheWhite80** [comment]
No I don't think I understand - sry :-(. In your latest zip are only ags* games, so this shouldn't be of concern now :-)

If you wan't a new/updated icon for "bladerunner-bladerunner-final" (just an example). Pls open a new iusse :-)

**Comment by GandalfTheWhite80** [comment]
I would add 
- ags-bcremake
- ags-detectivegallo
- ags-neofeud
- ags-skyfall
- ags-tftoz1
- ags-tftoz2

But I added alpha transparency to all of them. Pls have a look (discussion in discord :-) )
[output_advdef.zip](https://github.com/scummvm/scummvm-icons/files/9333412/output_advdef.zip)

**Comment by DavidAriyan** [comment]
> No I don't think I understand - sry :-(. In your latest zip are only ags* games, so this shouldn't be of concern now :-)
> 
> If you want a new/updated icon for "bladerunner-bladerunner-final" (just an example). Pls open a new iusse :-)

I included the Blade Runner icon in the separate zip called alt means "alternative" alone with other non ags icons. So users can choose to use this instead of the one in the official icons pack.
Ok thanks. I'll have a look at it when I have free time.
Just wait. I guess from now on I'll upload all update to google drive. Since GitHub won't allow it strangely.

**Comment by GandalfTheWhite80** [comment]
If you create new issues per game (even ags) we could link them to the task list above (better way would be add the game to the task list and use the button "covert to issue")

We don't have a concept for "alternative" icons - maybe this would be a feature request / an idee you could ask about in the discord channel?

The icon files are zips - so changing a game icon to a personal favorite is not so diffcult.

**Comment by DavidAriyan** [comment]
> If you create new issues per game (even ags) we could link them to the task list above (better way would be add the game to the task list and use the button "covert to issue")
> 
> We don't have a concept for "alternative" icons - maybe this would be a feature request / an idee you could ask about in the discord channel?
> 
> The icon files are zips - so changing a game icon to a personal favorite is not so diffcult.

I'll discuss this later. That is a good idea.

**Comment by DavidAriyan** [comment]
> If you create new issues per game (even ags) we could link them to the task list above (better way would be add the game to the task list and use the button "covert to issue")
> 
> We don't have a concept for "alternative" icons - maybe this would be a feature request / an idee you could ask about in the discord channel?
> 
> The icon files are zips - so changing a game icon to a personal favorite is not so diffcult.

I have a better idea,
I think im gonna remove wintermute icons from the alt.zip to new issue probably #305 as Wintermute icons.
But for the alternative icons, i just leave them here, since it's not that many, and I'm not planning to make more unless I'm not satisfied with the one in the scummvm official packs.

**Comment by DavidAriyan** [comment]
> No I don't think I understand - sry :-(. In your latest zip are only ags* games, so this shouldn't be of concern now :-)
> 
> If you want a new/updated icon for "bladerunner-bladerunner-final" (just an example). Pls open a new iusse :-)

In fact, if anybody want to use the alternative icons, like this blade runner, they just need to put the gui-icons-alt.dat to the icons path they had set along with other icons pack. No need to change anything to the official icons pack. The GUI all use the alternative version instead. Just try it.

**Comment by DavidAriyan** [comment]
> No I don't think I understand - sry :-(. In your latest zip are only ags* games, so this shouldn't be of concern now :-)
> 
> If you want a new/updated icon for "bladerunner-bladerunner-final" (just an example). Pls open a new iusse :-)

I DO want that my version of Blade Runner icon to be use in the official scummvm packs.
Since there are actually 2 version of icons available for Blade Runner: "bladerunner-bladerunner" (for regular version) & "bladerunner-bladerunner-final" (for the version with restored contents) .
But i have checked into the official packs they both use the similar icons with no difference.
Since this one is a special game an epic one i think,  better icon should be use at least for the "restored contents version". Please if you or anybody could. Please help me submit this Blade Runner icons to the official pack.

**Comment by GandalfTheWhite80** [comment]
The question is (for me) do we have a new game id dor the latest remake?  

- if not we should take this to the discussions
- Else make a new issue and name it 'balderunner-final icon update' or similar . And the we can discuss the Problem with the 3 versions and 2 ids

**Comment by DavidAriyan** [comment]
> The question is (for me) do we have a new game id dor the latest remake?
> 
> * if not we should take this to the discussions
> * Else make a new issue and name it 'balderunner-final icon update' or similar . And the we can discuss the Problem with the 3 versions and 2 ids

Tell me they're not similar. This is taken from the official icon packs
![Screenshot_20220815-005717_ZArchiver Pro~2](https://user-images.githubusercontent.com/78215839/184549027-9c46f4a6-d47c-46a3-b304-b12b6ea03697.png)
They actually use same icons for 2 version of this game. One of them should be change with the version i have here. At least for the bladerunner-bladerunner-final.

**Comment by GandalfTheWhite80** [comment]
i wasn't preise

The icons are 100% identical.  But we have 2 gameIds. One for the standard version and one for the 'final' version. But the final version was used before the current remake for the gog version.

**Comment by DavidAriyan** [comment]
> i wasn't precise
> 
> The icons (we have ) are 100% identical. But we have 2 gameIds. One for the standard version and one for the 'final' version. But the final version was used before the current remake for the gog version.

Dude, i don't think this game has anything to do with the 2022 remake of Blade Runner. That is a different game and only run on newer device like switch.
I'm not even talking about the remake.
The point is Blade Runner (classic) had 2 icons in the scummvm icon pack.
Or did i mistaken it? 
I don't know. But if you can, if possible, make the version here to the official pack. If not, it's still ok though. I still post it here in case anyone need it.
I gonna make more changes after this. Please give me time.

**Comment by DavidAriyan** [comment]
> i wasn't precise
> 
> The icons (we have ) are 100% identical. But we have 2 gameIds. One for the standard version and one for the 'final' version. But the final version was used before the current remake for the gog version.
> 
> The question: Are you refering to the gog version or to the new remake (2022)

Done. I had removed icons for other engines from the alt.zip and only left 3 icons, and primordia icon has been changed.
I also added your icons from the output_crused.zip to the main ags.zip.
I'm gonna open new issue for wintermute games and others. Because i found some really interesting games from those engine.

**Comment by DavidAriyan** [comment]
> i wasn't precise
> 
> The icons (we have ) are 100% identical. But we have 2 gameIds. One for the standard version and one for the 'final' version. But the final version was used before the current remake for the gog version.
> 
> The question: Are you refering to the gog version or to the new remake (2022)

About the task list you made above, do i need to check them or just you. I'm little confused. Because i already uploaded my icons right? Only this time to Drive.

**Comment by DavidAriyan** [comment]
> i wasn't precise
> 
> The icons (we have ) are 100% identical. But we have 2 gameIds. One for the standard version and one for the 'final' version. But the final version was used before the current remake for the gog version.
> 
> The question: Are you refering to the gog version or to the new remake (2022)

Take a look at these:
![Screenshot_20220815-015318_ScummVM~2](https://user-images.githubusercontent.com/78215839/184550993-32c93d66-5a7d-4b30-ac37-452fc47c090d.png)
Those are the same game. I use the same folder to displayed this.
This is appear when I'm about to add Blade Runner game to the Scummvm. I honestly don't know what difference about these two. Since they are the same game from the same folder. But can use different id and different icon as well.
![Screenshot_20220815-015428_ScummVM](https://user-images.githubusercontent.com/78215839/184550996-7ed03fbc-8c40-4445-a26c-f31c221581eb.png)
So what do you think?

**Comment by tag2015** [comment]
> I honestly don't know what difference about these two. Since they are the same game from the same folder. But can use different id and different icon as well.
> 
Technically it's the same game. The original game had some parts cut for various reasons, but the ScummVM developers managed to recover those parts (hence the "restored content"). However the restored version is not as stable as the other and the savegames aren't interchangeable, so instead of just a checkbox in the game options it got a different id.
IMHO the icons should be identical, maybe with an added wording at the bottom "restored content" with a similar style (to be honest I prefer the one without mccoy, it looks like the movie title screen)

**Comment by DavidAriyan** [comment]
> > I honestly don't know what difference about these two. Since they are the same game from the same folder. But can use different id and different icon as well.
> 
> Technically it's the same game. The original game had some parts cut for various reasons, but the ScummVM developers managed to recover those parts (hence the "restored content"). However the restored version is not as stable as the other and the savegames aren't interchangeable, so instead of just a checkbox in the game options it got a different id. IMHO the icons should be identical, maybe with an added wording at the bottom "restored content" with a similar style (to be honest I prefer the one without mccoy, it looks like the movie title screen)

Adding subtitle that it had restored contents is ridiculous. They should give it different icon.

**Comment by tag2015** [comment]
> Adding subtitle that it had restored contents is ridiculous. They should give it different icon.

Why is it ridiculous? Director's cut / GOTY versions usually use the same boxart, this is a similar situation. It's a matter of preference i guess.

**Comment by DavidAriyan** [comment]
It's called in my opinion. So don't take it personal.

**Comment by Thunderforge** [comment]
Discussing whether or not ScummVM should have two game ids for Blade Runner (`bladerunner` and `bladerunner-final`) is a conversation that is bigger than just this PR. For the time being, the two of them exist and we need icons for both. Whether they are the same or different is an open question.

Maybe it would be better to move Blade Runner to a separate issue and we could discuss it individually?

**Comment by DavidAriyan** [comment]
> Discussing whether or not ScummVM should have two game ids for Blade Runner (`bladerunner` and `bladerunner-final`) is a conversation that is bigger than just this PR. For the time being, the two of them exist and we need icons for both. Whether they are the same or different is an open question.
> 
> Maybe it would be better to move Blade Runner to a separate issue and we could discuss it individually?

Yeah, i think I should. I'll make separate issue for Blade Runner.

**Comment by GandalfTheWhite80** [comment]
As far as I can the the only "missing" icons (we have not added so far) are icons without text/title. On the other hand as far as I know all our icons have a text/title.

Could you add a title to this last ones?

**Comment by tag2015** [comment]
I'll see if I can complete/improve the remaining icons so we can eventually close this

**Comment by tag2015** [comment]
Uploaded 6 icons, just 3 to go (plus one MIA)

**Comment by tag2015** [comment]
"Da New Guys" and "Da New Guys: Day of The Jackass" are two different games.
The icon for the first one is already part of the set, while the latter is not yet available. Marked the task as such

**Comment by tag2015** [comment]
Uploaded superego and beyondhorizon (not too happy with this one, though)

I suggest keeping the issue open to see if @DavidAriyan comments about the "Enclosure" icon, then it can be closed

**Comment by DavidAriyan** [comment]
> Uploaded superego and beyondhorizon (not too happy with this one, though)
> 
> I suggest keeping the issue open to see if @DavidAriyan comments about the "Enclosure" icon, then it can be closed

The Enclosure game is not ags I'm aware back then someone informed me about it. I'm unable to make any edit to the icons, I'm busy right now with work. And can't find spare time to make new icons. I'm sorry about that.
Thank you for updating it. I'll probably come back later

**Comment by tag2015** [comment]
Ok, then I think the issue can be closed, as this tasklist is complete
