### ISSUE TITLE
New icon for Blade Runner (With Restored Contents/ Final)

### ISSUE THREAD

**Issue by DavidAriyan** [scummvm/scummvm-icons#305]
I decided to make a custom icon for a game that can be called epic cyberpunk adventure in it's time: Blade Runner (1997).
after looking through the scummvm's official icons pack, i found that the game has two different icons for different version: bladerunner-bladerunner.png &
bladerunner-bladerunner-final.png.
But strangely it use two similar or even the same icon. That only show the game title.
I made an alternative icon at least for the Blade Runner (Final). It still the classic game, not the 2022 remake but it has restored contents.
This is the source:
https://en.wikipedia.org/wiki/File%3ABladeRunner_PC_Game_%28Front_Cover%29.jpg
Using some enchantments here and there. Through AI rasterization. And colors corrections. 
And this is the result:
![IMG_1660601872034](https://user-images.githubusercontent.com/78215839/184728069-2651c9d3-a302-4f50-8a80-c7d261bb8d4b.png)
It's not perfect, but i think this should be good enough to be use for the scummvm GUI icon.
And this is the raw higher resolution version:
[bladerunner-bladerunner-final.zip](https://github.com/scummvm/scummvm-icons/files/9340152/bladerunner-bladerunner-final.zip)

As per request, i propose this to be the second icon for the Blade Runner game, precisely for the final version.
I needed others opinion about this.
Thank you.

**Comment by GandalfTheWhite80** [comment]
added your icon as "bladerunner-bladerunner" and used your icon as a base version for the "RESTORED CONTENT" bladerunner-final version.

Thx a lot!

**Comment by DavidAriyan** [comment]
You're welcome. Glad this has been done.
