### ISSUE TITLE
Icon for The Adventures of Fatman

### ISSUE THREAD

**Issue by joeraz** [scummvm/scummvm-icons#306]
I created this icon for the AGS game The Adventures of Fatman.  Can you use it, or does it need some adjustments?

(Please credit WhiteRakogis for the icon)

![Fatman](https://user-images.githubusercontent.com/2691813/185796690-0c2aa1a5-6724-4ca0-a840-472c6caecb90.png)

Thanks.

**Comment by GandalfTheWhite80** [comment]
BTW- do you know the correct game id? (advdev is runnig)

**Comment by GandalfTheWhite80** [comment]
Done - added -> THX!
