### ISSUE TITLE
Pink-Pokus icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#308]
Updated Pink Panther
![Pink-Pokus](https://user-images.githubusercontent.com/61733979/194671191-41a4029d-ea32-48fb-a87b-15f074997505.png)

**Comment by GandalfTheWhite80** [comment]
Used your version and made a "sharper" version - I could live with your version :-)

![image](https://user-images.githubusercontent.com/71585967/194596419-b1d6b479-c0b6-451d-bca9-44efc0e17713.png)

**Comment by Thunderforge** [comment]
The panther looks much more blurry to me than the other two figures, especially around his feet (contrast with the text near him). Can you confirm that this is the way that it's supposed to be?

**Comment by GandalfTheWhite80** [comment]
Not "supposed" but indeed :-) :-(  maybe combin pather (feet/legs) with the rest?

**Comment by GandalfTheWhite80** [comment]
![pink-pokus-v2](https://user-images.githubusercontent.com/71585967/194617158-71e0a6a2-35ee-4f46-aa5c-55d872179b51.png)

I could "combine" it (but I don't have time till tomorrow evening) - feel free :-)

**Comment by Tucky27** [comment]
I updated the pink panther to not have an outline. Initially I did that so eyebrows and whiskers would show on a dark background so I've kept the outline there and removed elsewhere.

**Comment by GandalfTheWhite80** [comment]
Nice! 

Used the "smother" title in this version. Is this Ok for you?

![pink-pokus-v5](https://user-images.githubusercontent.com/71585967/194717420-e5b1646c-902d-4e67-ba40-40b51d6dee44.png)

**Comment by Tucky27** [comment]
> Nice!
> 
> Used the "smother" title in this version. Is this Ok for you?
> 
> ![pink-pokus-v5](https://user-images.githubusercontent.com/71585967/194717420-e5b1646c-902d-4e67-ba40-40b51d6dee44.png)

All good.

**Comment by Thunderforge** [comment]
I'm okay with this version.

**Comment by GandalfTheWhite80** [comment]
Added - Thx!
