### ISSUE TITLE
Add missing icons for games on the website Compatibility page

### ISSUE THREAD

**Issue by Thunderforge** [scummvm/scummvm-icons#310]
The ScummVM website contains a [compatibility page](https://www.scummvm.org/compatibility/) of all the games officially supported by the project. We should have icons for all these games, but a number of them are missing and should be created.

* [x] `ags:goldenwake` — *A Golden Wake*
* [x] `ags:sq45` — *Space Quest IV.5 - Roger Wilco and the Voyage Home*
* [x] `freescape:driller` — *Driller*
* [x] `glk:corruption` — *Corruption*
* [x] `glk:fish` — *Fish!*
* [x] `glk:guild` — *The Guild of Thieves*
* [x] `glk:jinxter` — *Jinxter*
* [x] `glk:myth` — *Myth*
* [x] `glk:pawn` — *The Pawn*
* [x] `icb:icb` — *In Cold Blood*
* [x] `mtropolis:obsidian` — *Obsidian*
* [x] `petka:petka1` — *Red Comrades 1: Save the Galaxy*
* [x] `petka:petka2` — *Red Comrades 2: For the Great Justice*
* [x] `pink:peril` — *The Pink Panther: Passport to Peril*
* [x] `private:private-eye` — *Private Eye*
* [x] `sci:hoyle4` — *Hoyle Classic Card Games*
* [x] `sci:hoyle5` — *Hoyle Classic Games*
* [x] `sci:hoyle5solitaire` — *Hoyle Solitaire*
* [x] `tsage:ringworld2` — *Return to Ringworld*
* [x] `wintermute:5ld` — *Five Lethal Demons*
* [x] `wintermute:5ma` — *Five Magical Amulets*
* [x] `wintermute:bickadoodle` — *Bickadoodle*
* [x] `wintermute:deadcity` — *Dead City*
* [x] `wintermute:dirtysplit` — *Dirty Split*
* [x] `wintermute:escapemansion` — *Escape from the Mansion*
* [x] `wintermute:helga` — *Helga Deep In Trouble*
* [x] `wintermute:ritter` — *1½ Ritter: Auf der Suche nach der hinreißenden Herzelinde*
* [x] `wintermute:rosemary` — *Rosemary*
* [x] `wintermute:twc` — *The White Chamber*
* [x] `xeen:darksideofxeen` — *Might and Magic: Darkside of Xeen*
* [x] `xeen:swordsofxeen` — *Might and Magic: Swords of Xeen*
* [x] `xeen:worldofxeen` — *Might and Magic: World of Xeen*

**Comment by GandalfTheWhite80** [comment]
private-private-eye -> was already there

**Comment by tag2015** [comment]
It'd be nice to also have icons for the enhanced Ultimas
Ultima IV Enhanced (ultima4_enh)
Ultima VI Enhanced (ultima6_enh)

**Comment by tag2015** [comment]
Two minor things:
- The mystme target is not used (shared with myst), should be removed
- In cold blood is not supported yet, should be removed or low priority

**Comment by Thunderforge** [comment]
> The mystme target is not used (shared with myst), should be removed

Confirmed. This list was from the website, but that doesn't match the ScummVM code. It seems that in the past, `mystme` was a separate id.

**Comment by tag2015** [comment]
Added the missing GLK Magnetic Scrolls icons

**Comment by tag2015** [comment]
Added pink-peril and 3 wintermute icons

**Comment by tag2015** [comment]
Added the 2 AGS games, hoyle and ringworld2

**Comment by tag2015** [comment]
Added bickadoodle, ritter, escapemansion and rosemary

**Comment by GandalfTheWhite80** [comment]
last (missing) icon proposal is in discord :-)

**Comment by GandalfTheWhite80** [comment]
done :-)

**Comment by Thunderforge** [comment]
Thank you to everyone who helped!
