### ISSUE TITLE
Some thoughts about the current icons

### ISSUE THREAD

**Issue by tag2015** [scummvm/scummvm-icons#311]
Not really an issue, just (personal) thoughts about some of the icons:

- sword1: The goat is a staple of the series, but I think it's not very fitting here. It'd probably be better to use the boxart (like sword2) or just the title (DONE)
- blueforce: Needs a border or something, almost unreadable on dark backgrounds (DONE)
- indy3 & indy4: Very similar, hard to tell one from the other when zoomed out. Maybe add some art?
- kathyrain: A bit small. It'd look better cropped (e.g. cutting off the buildings at the sides of the title) (DONE)
- maniac mansion deluxe: Alignment is off, it would probably look better if the red rightmost trail is removed/trimmed and recentered

**Comment by GandalfTheWhite80** [comment]
blueforce/kathy - I have a "work-in-progress" version of both icons - I'll need a few days (or a week) -> will post it in the discord channel.

ManciaDeluxe - maybe we could use the text / title from the maniac icon ?

**Comment by tag2015** [comment]
The issues are solved, with the exception of the indy3-4 icons. I opened a new ticket with other issues, so closing this one
