### ISSUE TITLE
ICONS: Add icon for Cedric and the revolution

### ISSUE THREAD

**Issue by marus70** [scummvm/scummvm-icons#313]
![engine - cedricandtherevolution](https://user-images.githubusercontent.com/37115947/214066794-c505d08f-717f-4ef4-b618-3caaba7e1d83.png)

Thank you

**Comment by GandalfTheWhite80** [comment]
- what do you think about removing this black borders?
- or about a "smother" version`?

![ags-cedricandtherevolution](https://user-images.githubusercontent.com/71585967/214142511-ac11f63c-8a8a-40d6-8826-2331da76b483.png)

**Comment by marus70** [comment]
> * what do you think about removing this black borders?
> * or about a "smother" version`?
> 
> ![ags-cedricandtherevolution](https://user-images.githubusercontent.com/71585967/214142511-ac11f63c-8a8a-40d6-8826-2331da76b483.png)

Sure yours is better, I added black borders just to reach 1:1 format (512px X 512 px)

**Comment by marus70** [comment]
So we can consider the one by Gandalf the good one, do this will be in the next pack update?
Thanks.

**Comment by GandalfTheWhite80** [comment]
I will upload it in the next hour.

**Comment by GandalfTheWhite80** [comment]
Done
