### ISSUE TITLE
Create icons for games added in ScummVM 2.8.0

### ISSUE THREAD

**Issue by Thunderforge** [scummvm/scummvm-icons#331]
The following games were added in ScummVM 2.8.0:

- [x] [Adibou 1](https://wiki.scummvm.org/index.php?title=Adibou_1) (`gob-adibou1`)
- [x] [Alice: An Interactive Museum](https://wiki.scummvm.org/index.php?title=Alice:_An_Interactive_Museum) (`director-alice`)
- [x] Ape Odyssey 2001 (`director-apeodyssey`)
- [x] Classical Cats (`director-classicalcats`)
- [x] The Cute Machine (`director-cutemachine`)
- [x] [The Dark Eye](https://wiki.scummvm.org/index.php?title=The_Dark_Eye) (`director-darkeye`)
- [x] [Dark Side](https://wiki.scummvm.org/index.php?title=Dark_Side) (`freescape-darkside`)
- [x] [Escape From Hell](https://wiki.scummvm.org/index.php?title=Escape_from_Hell) (`efh-efh`)
- [x] [Gadget: Invention, Travel and Adventure](https://wiki.scummvm.org/index.php?title=Gadget:_Invention,_Travel,_%26_Adventure) (`director-gadget`)
- [x] [Kingdom](https://wiki.scummvm.org/index.php?title=Kingdom:_The_Far_Reaches) (`kingdom-kingdom`)
- [x] [Might and Magic: Book One - Secret of the Inner Sanctum](https://wiki.scummvm.org/index.php?title=Might_and_Magic_Book_One:_The_Secret_of_the_Inner_Sanctum) (`mm1-mm1`)
- [x] [Muppet Treasure Island](https://wiki.scummvm.org/index.php?title=Muppet_Treasure_Island) (`mtropolis-mti`)
- [x] [Nancy Drew: Secrets Can Kill](https://wiki.scummvm.org/index.php?title=Nancy_Drew:_Secrets_Can_Kill) (`nancy-nancy1`)
- [x] [Nancy Drew: Stay Tuned for Danger](https://wiki.scummvm.org/index.php?title=Nancy_Drew:_Stay_Tuned_for_Danger) (`nancy-nancy2`)
- [x] [Nancy Drew: Message in a Haunted Mansion](https://wiki.scummvm.org/index.php?title=Nancy_Drew:_Message_in_a_Haunted_Mansion) (`nancy-nancy3`)
- [x] [Nancy Drew: Treasure in the Royal Tower](https://wiki.scummvm.org/index.php?title=Nancy_Drew:_Treasure_in_the_Royal_Tower) (`nancy-nancy4`)
- [x] [Nancy Drew: The Final Scene](https://wiki.scummvm.org/index.php?title=Nancy_Drew:_The_Final_Scene) (`nancy-nancy5`)
- [x] [Reah: Face the Unknown](https://wiki.scummvm.org/index.php?title=Reah:_Face_the_Unknown) (`vcruise-reah`)
- [x] [Schizm: Mysterious Journey](https://wiki.scummvm.org/index.php?title=Schizm:_Mysterious_Journey) (`vcruise-schizm`)
- [x] [Syberia](https://wiki.scummvm.org/index.php?title=Syberia) (`tetraedge-syberia`)
- [x] [Syberia II](https://wiki.scummvm.org/index.php?title=Syberia_II) (`tetraedge-syberia2`)
- [x] [The Vampire Diaries](https://wiki.scummvm.org/index.php?title=The_Vampire_Diaries) (`nancy-vampirediaries`)
- [x] Wrath of the Gods (`director-wrath`)

We should make sure that they all have icons before release.

**Comment by Thunderforge** [comment]
Added the seven newly supported Director titles listed in [this news item](https://www.scummvm.org/news/20231214/).

**Comment by tag2015** [comment]
I just noticed that
[Halls of the Dead: Faery Tale Adventure 2](https://www.mobygames.com/game/3414/halls-of-the-dead-faery-tale-adventure-ii/) (`saga2-fta2`)
is also missing the icon. The game was added in version 2.7.0

**Comment by GandalfTheWhite80** [comment]
added saga2-fta2

**Comment by GandalfTheWhite80** [comment]
I couldn't find any valid cover etc for the remaining 3 games.

**Comment by GandalfTheWhite80** [comment]
@Thunderforge close ?
