### ISSUE TITLE
Document how to manually install ScummVM icons

### ISSUE THREAD

**Issue by ssokolow** [scummvm/scummvm-icons#336]
I spent a long, frustrating waste of time trying to get these installed manually on a retro-hobby machine before giving up, temporarily granting unfiltered access to the Internet, and discovering they were expected to be in a completely different format.

1. I tried using the download button in ScummVM, only to discover it ignores the system's HTTP/HTTPS proxy settings, so it couldn't see the Internet.
1. I tried just putting the contents of the `icons` folder from the repo into the Icons folder... no dice.
2. I tried putting the entire `default` folder into the Icons folder... no dice.
3. I tried both of those with the icon path explicitly set to Icons... no dice.
4. I thought "OK, I'll temporarily allow network for the Flatpak-installed copy of ScummVM on my Linux machine and see what it does." ...no dice because I'd forgotten I tried something similar and pointed the icons path at a read-only directory elsewhere on the system and I got an unhelpful permission denied error.
5. I tried googling around, but couldn't find any results that were helpful.

Please add something to the README to prevent others from making the same mistake.

**Comment by GandalfTheWhite80** [comment]
I'm sorry for your trouble:-(. I think most people will install the icons by using the gui dl button.

But we could add that you can just put your icons into a zip file into the corect folder.

**Comment by ssokolow** [comment]
That'd be a big help.

I really prefer to download stuff manually, put it in sorted archival folders, and then install from the archival folders as a sort of human-centric version of how Flatpak breaks the build into a manifest-driven download phase that can't run arbitrary code and a build phase that can't download files.

**Comment by GandalfTheWhite80** [comment]
You can put your icons in a <date>.dat file (the dat file is a standard zip file). You can choose the current date 20241017.dat (if i'm not mistaken) and put this file into scummvm/icons . (Icons should be the default path but you cann change it in the scummvm.ini or the gui)

**Comment by ssokolow** [comment]
By the time I posted this, I'd already resorted to letting ScummVM download them on one machine, archiving what it downloaded, and then manually installing the archived dat files on another machine where ScummVM had no Internet access to make sure I understood what's going on.

The problem is, that's akin to giving up and using Steam to download DRM-free games in violation of my policy to never buy things that need specialized downloaders. I'm trying to make sure nobody else has to compromise like that.

(Granted, if I weren't so frustrated, I'd have had the patience to just stick to my principles and start reading the ScummVM source code to figure out what I was doing wrong.)

**Comment by GandalfTheWhite80** [comment]
Well , maybe you could ask your questions on the scummvm discord server (if you have any further questions).

https://discord.gg/4cDsMNtcpG

**Comment by ssokolow** [comment]
I think there's some kind of breakdown in communication here.

I have no more questions to ask. I'm trying to get the documentation improved for people who wind up in my situation in the future.

**Comment by criezy** [comment]
The official documentation for ScummVM is at https://docs.scummvm.org/ and there is a link to it in the side menu on https://www.scummvm.org/.

That documentation can certainly be improved. Regarding icons pack there is something on this page for manual installs: https://docs.scummvm.org/en/v2.8.0/settings/gui.html#updateicons
> The icon packs can also be downloaded manually from https://downloads.scummvm.org/frs/icons/ and must be placed in the [Icon Path](https://docs.scummvm.org/en/v2.8.0/settings/paths.html#iconspath). The packs are incremental and you need all of them to have all the available icons and not just the most recent pack.

Based on what was confusing to you, do you have suggestion to improve these instructions?

**Comment by ssokolow** [comment]
I somehow missed those instructions and wound up at this repo, so it'd be a good idea to have something in the README that points users back toward those docs if they want to do a manual install.

**Comment by criezy** [comment]
Thank you for the feedback. I have updated the README to point to the documentation for instructions on how to use the icons.
