### ISSUE TITLE
Icons required for the upcoming 2.9.0 release

### ISSUE THREAD

**Issue by tag2015** [scummvm/scummvm-icons#338]
Several newly supported games are still without an icon. It'd be nice to address the issue before the 2.9.0 release

- [x] bagel-spacebar : The Space Bar
- [x] crab-unrest : Unrest
- [x] dgds-rise : Rise of the Dragon
- [x] freescape-totaleclipse2 : Total Eclipse II
- [x] qdengine-nupogodi3 : Wait for it! Issue 3. Song for a hare (Ну, погоди! Выпуск 3. Песня для зайца)
- [x] qdengine-maski : Mask Show (Маски-шоу)
- [x] qdengine-3mice1 : Marvellous Mice Adventures: Meeting Sea Rat (Три маленькие белые мышки. Визит Морской крысы)
- [x] qdengine-shveik : The Adventures of the Good Soldier Schweik (Похождения бравого солдата Швейка)
- [x] qdengine-3mice2 : Marvellous Mice Adventures: Sea Rat's Birthday, (Три маленькие белые мышки. День рождения морской крысы)

I'm working on a few AGS game icons but as those are not high priority I won't list them here.

**Comment by GandalfTheWhite80** [comment]
I will start "top down" - I have some ideas for the first 4 games.

**Comment by GandalfTheWhite80** [comment]
Any further icons?

**Comment by tag2015** [comment]
Sure, thanks for the work!
I also updated issue #322 if you want to have a look
