### ISSUE TITLE
Missing platform icon for Amstrad CPC

### ISSUE THREAD

**Issue by ccawley2011** [scummvm/scummvm-icons#339]

**Comment by GandalfTheWhite80** [comment]
Are there games taged with this platform? Any suggestions for an icon ?

**Comment by tag2015** [comment]
> Are there games taged with this platform? Any suggestions for an icon ?

Only in the freescape engine I think

This is the computer (you can see logo in the middle)
https://www.reddit.com/media?url=https%3A%2F%2Fpreview.redd.it%2Fyety4l8wjxl21.jpg%3Fwidth%3D1080%26crop%3Dsmart%26auto%3Dwebp%26s%3D50f018a77679d3a81eab4f05d7ba1dc91f68eea4

An example
https://seeklogo.com/vector-logo/534346/amstrad-cpc

**Comment by GandalfTheWhite80** [comment]
Ok making a square 64x64px icon could be interesting 😁

**Comment by GandalfTheWhite80** [comment]
![cpc](https://github.com/user-attachments/assets/b21dff28-8296-4cc9-93d2-c37bfc4a3afc)
Added cpc.png (and the svg for future use). The platform icon was discussed in detail in the discord channel :-).
