### ISSUE TITLE
New Icon Submission for AGS Game "The Phantom Fellows"

### ISSUE THREAD

**Issue by thevolumeremote** [scummvm/scummvm-icons#341]
#### Game Icon Submission
[ags-thephantomfellows.png.zip](https://github.com/user-attachments/files/18241892/ags-thephantomfellows.png.zip)

- **Game Name:** The Phantom Fellows
- **Game Engine:** AGS
- **Game ID:** thephantomfellows
- **Icon Size:** 512x512
- **File Format:** PNG with transparent background

#### Additional Information
- Please credit me as **Paul Korman**.

**Comment by GandalfTheWhite80** [comment]
Thx four your submission. I will have a closer look / add it after the holidays.

We made a new icon.dat file very recently. (It may take a while until the icon is visible/dl).

Thx a lot

**Comment by GandalfTheWhite80** [comment]
PS we have already have an icon for this game. Your intention is to update the current icon?

https://github.com/scummvm/scummvm-icons/blob/master/icons/ags-phantomfellows.png

**Comment by thevolumeremote** [comment]
Hi! Yes I’d like to update the icon to this new one please—the previous one is from the old demo version and since then the text logo and art was improved a lot :) 

and for the game ID’s I submitted to bugtracker today, they’re for the same game phantomfellows (The Phantom Fellows) but they’re the new versions. More specifically they’re the ID’s for the public release of the full game (one ID is for Steam and the other GOG). 

I’m (probably obviously) the developer and I just love ScummVM so much that I wanna get my game looking mint and working great in ScummVM. Thank you so much for your help!

**Comment by GandalfTheWhite80** [comment]
Thx for your explanation!

I think we have only one gameid for the different versions. But we can mark demo versions :-)

As already mentioned.  I will add/update it after the holidays.  Normally i will run advdef and/or advpng on the submitted files. And for this i need my pc :-)

**Comment by thevolumeremote** [comment]
Thank you so much! And yes there’s one gameid for now but about an hour ago I submitted 2 new gameids through bugtracker—so the single ID in ScummVM now is the demo, and the two new ones I submitted today will both be for the full release :)

thank you again for your time with this, I hope you have a lovely holiday :)

**Comment by GandalfTheWhite80** [comment]
Have some nice holiday too.

Btw can you share me the bugtracker links. Then i can watch them?

**Comment by thevolumeremote** [comment]
Thanks for keeping an eye out, I appreciate you :)

https://bugs.scummvm.org/ticket/15618

**Comment by GandalfTheWhite80** [comment]
updated the icon / didn't pay attention to the icon size. In your zip the icon has 600x600px. I have downsized it with "no scaler" (to preserve the pixelated look). I will update it later
