### ISSUE TITLE
agos-simon1 + agos-simon2 icon

### ISSUE THREAD

**Issue by GandalfTheWhite80** [scummvm/scummvm-icons#37]
Attached 2 icons for agos-simon1 and agos-simon2.

[agos-simon2.zip](https://github.com/scummvm/scummvm-icons/files/5251310/agos-simon2.zip)
[agos-simon1.zip](https://github.com/scummvm/scummvm-icons/files/5251311/agos-simon1.zip)

**Comment by SupSuper** [comment]
Thanks for your contribution!
