### ISSUE TITLE
Icons for Putt-Putt and Freddi games

### ISSUE THREAD

**Issue by Retrodude94** [scummvm/scummvm-icons#40]
[scumm-putt-freddi.zip](https://github.com/scummvm/scummvm-icons/files/5264036/scumm-putt-freddi.zip)
Icons for remaining Putt-Putt and Freddi adventure games
If used, credit simply to "Retrodude".
Let me know if there are any issues.

**Comment by SupSuper** [comment]
Looks good, thanks!
