### ISSUE TITLE
Icon for Arthur's Teacher Troubles

### ISSUE THREAD

**Issue by mileso** [scummvm/scummvm-icons#48]
Sample Living Books icon for Arthur's Teacher Troubles.  This is adapted from a logo I created for CoinOps (actually CoinOpsX on the Arcade Legends Ultimate).  If this is suitable I have another dozen or so I can adapt.
[mohawk-arthur.zip](https://github.com/scummvm/scummvm-icons/files/5330506/mohawk-arthur.zip)

**Comment by SupSuper** [comment]
Looks great, feel free to submit more.
