### ISSUE TITLE
scumm-bear-stormin' Icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#59]
[scumm-Bear-Stormin' Icon.zip](https://github.com/scummvm/scummvm-icons/files/5401859/scumm-Bear-Stormin.Icon.zip)
![scumm-Bear-Stormin'](https://user-images.githubusercontent.com/61733979/96453510-1359ea00-1277-11eb-88dd-0dfb9771e407.png)

**Comment by SupSuper** [comment]
In the future please use the **Game ID** in the filenames, not the title. (eg. `scumm-brstorm.png`).
