### ISSUE TITLE
Secret & Curse of Monkey Island Icons

### ISSUE THREAD

**Issue by lI4Nl** [scummvm/scummvm-icons#6]
![SOMI](https://user-images.githubusercontent.com/49815206/92335617-b0cad700-f098-11ea-8464-a1a98af9a3ed.png)
![COMI](https://user-images.githubusercontent.com/49815206/92335618-b1636d80-f098-11ea-8804-51000dce0a88.png)

**Comment by lI4Nl** [comment]
ERRATUM
![scumm-monkey](https://user-images.githubusercontent.com/49815206/92335651-20d95d00-f099-11ea-9c01-5a2eb33fc261.png)
![scumm-comi](https://user-images.githubusercontent.com/49815206/92335653-2171f380-f099-11ea-9cc7-ce966ae6e19b.png)

**Comment by JenniBee** [comment]
Just a note to the ScummVM Icon repository maintainers: I submitted Pull request #7 which included these two icons, but feel free to use these icons instead. I'd hate to see lI4Nl's work go to waste.

**Comment by SupSuper** [comment]
@JenniBee They're basically identical as far as I can tell, so I merged yours. We might need a way to avoid overlapping submissions.
