### ISSUE TITLE
Scumm- Blue's Reading Time Activities Icon

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#70]
[scumm-readtime Icon.zip](https://github.com/scummvm/scummvm-icons/files/5586521/scumm-readtime.Icon.zip)
![scumm-readtime](https://user-images.githubusercontent.com/61733979/100029582-79c5bf80-2e56-11eb-9a3c-a50bee90b576.png)

**Comment by SupSuper** [comment]
Sorry for the delay!

**Comment by sev-** [comment]
Hey, @Tucky27 Could you please drop me a line at sev@scummvm.org?
