### ISSUE TITLE
SPY Fox 3-Operation Ozone & A Stroke of Fate - Operation Valkyrie Icons

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#8]
![Wintermute-A Stroke of Fate - Operation Valkyrie](https://user-images.githubusercontent.com/61733979/92343993-5756bc80-f119-11ea-865f-57406d98a5ab.png)
![Scumm-SPY Fox 3-Operation Ozone](https://user-images.githubusercontent.com/61733979/92343998-5a51ad00-f119-11ea-8b4d-6b7e14b4ceab.png)

**Comment by Tucky27** [comment]
![Scumm-SPY Fox 3-Operation Ozone](https://user-images.githubusercontent.com/61733979/92343094-eadabe00-f116-11ea-872a-563543f029e1.png)

**Comment by Tucky27** [comment]
![Scumm-SPY Fox 3-Operation Ozone](https://user-images.githubusercontent.com/61733979/92343733-a3edc800-f118-11ea-8b01-c906b723108f.png)

**Comment by JenniBee** [comment]
I believe _A Stroke of Fate: Operation Valkarie_ is a 2.5D Wintermute title, so will be supported by ResidualVM rather than ScummVM.

**Comment by Tucky27** [comment]
Its listed in the table of contents which is what I'm going on. If there are any that games that scummvm team would rather we ignore, is it written up somewhere?
https://github.com/scummvm/scummvm-icons/blob/master/TOC.md

**Comment by SupSuper** [comment]
@Tucky27 Thanks! In the future ZIP your icons, to avoid Github renaming them.

@JenniBee Nice catch, I've removed the unstable Wintermute games to avoid confusion.
