### ISSUE TITLE
ICON: Bear Stormin' Update

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#82]
[scumm-brstorm.zip](https://github.com/scummvm/scummvm-icons/files/6641645/scumm-brstorm.zip)
![scumm-brstorm](https://user-images.githubusercontent.com/61733979/121764797-b5c63500-cb9a-11eb-94b0-3435609c728e.png)

**Comment by SupSuper** [comment]
@Tucky27 Have you considered learning Git? That way you could contribute to us directly. :)
