### ISSUE TITLE
ICON: Little Big Adventure

### ISSUE THREAD

**Issue by Tucky27** [scummvm/scummvm-icons#83]
[twine-lba.zip](https://github.com/scummvm/scummvm-icons/files/7063471/twine-lba.zip)
![twine-lba](https://user-images.githubusercontent.com/61733979/131055286-f43d36b2-92e8-4324-9dc1-94e075f41496.png)

**Comment by SupSuper** [comment]
Thanks. Twinsen does look goofy in the covers, but I think that's what players will recognize.
